// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/profile/profile.proto

package profile

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Profile struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ImName          string                 `protobuf:"bytes,4,opt,name=im_name,json=imName,proto3" json:"im_name,omitempty"`
	Avatar          string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Age             int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	Gender          string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	BirthLocation   string                 `protobuf:"bytes,9,opt,name=birth_location,json=birthLocation,proto3" json:"birth_location,omitempty"`
	CurrentLocation string                 `protobuf:"bytes,10,opt,name=current_location,json=currentLocation,proto3" json:"current_location,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AvatarFileId    string                 `protobuf:"bytes,13,opt,name=avatar_file_id,json=avatarFileId,proto3" json:"avatar_file_id,omitempty"` // 头像文件ID
	Intro           string                 `protobuf:"bytes,14,opt,name=intro,proto3" json:"intro,omitempty"`                                     // 个人简介
	Custom          []*Property            `protobuf:"bytes,15,rep,name=custom,proto3" json:"custom,omitempty"`                                   // 自定义属性
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetImName() string {
	if x != nil {
		return x.ImName
	}
	return ""
}

func (x *Profile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Profile) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Profile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Profile) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *Profile) GetBirthLocation() string {
	if x != nil {
		return x.BirthLocation
	}
	return ""
}

func (x *Profile) GetCurrentLocation() string {
	if x != nil {
		return x.CurrentLocation
	}
	return ""
}

func (x *Profile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Profile) GetAvatarFileId() string {
	if x != nil {
		return x.AvatarFileId
	}
	return ""
}

func (x *Profile) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *Profile) GetCustom() []*Property {
	if x != nil {
		return x.Custom
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ListProfilesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 搜索名称
	SearchName string `protobuf:"bytes,1,opt,name=search_name,json=searchName,proto3" json:"search_name,omitempty"`
	// id
	Ids []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	// 分页
	PageToken string `protobuf:"bytes,21,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// 每页大小
	PageSize      string `protobuf:"bytes,22,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *ListProfilesRequest) GetSearchName() string {
	if x != nil {
		return x.SearchName
	}
	return ""
}

func (x *ListProfilesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListProfilesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListProfilesRequest) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *ListProfilesResponse) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ListProfilesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImName        string                 `protobuf:"bytes,2,opt,name=im_name,json=imName,proto3" json:"im_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"` // 保留以兼容旧版本
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Age           int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	Intro         string                 `protobuf:"bytes,7,opt,name=intro,proto3" json:"intro,omitempty"`
	Custom        []*Property            `protobuf:"bytes,8,rep,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetImName() string {
	if x != nil {
		return x.ImName
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateProfileRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *CreateProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateProfileRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateProfileRequest) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *CreateProfileRequest) GetCustom() []*Property {
	if x != nil {
		return x.Custom
	}
	return nil
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImName        string                 `protobuf:"bytes,3,opt,name=im_name,json=imName,proto3" json:"im_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Profile       string                 `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`                                 // 保留以兼容旧版本
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`                                   // 性别字段 (male/female)
	AvatarFileId  string                 `protobuf:"bytes,7,opt,name=avatar_file_id,json=avatarFileId,proto3" json:"avatar_file_id,omitempty"` // 头像文件ID
	Age           int32                  `protobuf:"varint,8,opt,name=age,proto3" json:"age,omitempty"`
	Intro         string                 `protobuf:"bytes,9,opt,name=intro,proto3" json:"intro,omitempty"`
	Custom        []*Property            `protobuf:"bytes,10,rep,name=custom,proto3" json:"custom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetImName() string {
	if x != nil {
		return x.ImName
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarFileId() string {
	if x != nil {
		return x.AvatarFileId
	}
	return ""
}

func (x *UpdateProfileRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateProfileRequest) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *UpdateProfileRequest) GetCustom() []*Property {
	if x != nil {
		return x.Custom
	}
	return nil
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_proto_profile_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_proto_profile_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_profile_proto_rawDescGZIP(), []int{11}
}

var File_proto_profile_profile_proto protoreflect.FileDescriptor

const file_proto_profile_profile_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/profile/profile.proto\x12\aprofile\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"4\n" +
	"\bProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x88\x04\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x17\n" +
	"\aim_name\x18\x04 \x01(\tR\x06imName\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x126\n" +
	"\bbirthday\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12%\n" +
	"\x0ebirth_location\x18\t \x01(\tR\rbirthLocation\x12)\n" +
	"\x10current_location\x18\n" +
	" \x01(\tR\x0fcurrentLocation\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x0eavatar_file_id\x18\r \x01(\tR\favatarFileId\x12\x14\n" +
	"\x05intro\x18\x0e \x01(\tR\x05intro\x12)\n" +
	"\x06custom\x18\x0f \x03(\v2\x11.profile.PropertyR\x06custom\"#\n" +
	"\x11GetProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.profile.ProfileR\aprofile\"\x84\x01\n" +
	"\x13ListProfilesRequest\x12\x1f\n" +
	"\vsearch_name\x18\x01 \x01(\tR\n" +
	"searchName\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"page_token\x18\x15 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x16 \x01(\tR\bpageSize\"l\n" +
	"\x14ListProfilesResponse\x12,\n" +
	"\bprofiles\x18\x01 \x03(\v2\x10.profile.ProfileR\bprofiles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xe0\x01\n" +
	"\x14CreateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aim_name\x18\x02 \x01(\tR\x06imName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12\x14\n" +
	"\x05intro\x18\a \x01(\tR\x05intro\x12)\n" +
	"\x06custom\x18\b \x03(\v2\x11.profile.PropertyR\x06custom\"C\n" +
	"\x15CreateProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.profile.ProfileR\aprofile\"\x96\x02\n" +
	"\x14UpdateProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aim_name\x18\x03 \x01(\tR\x06imName\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x18\n" +
	"\aprofile\x18\x05 \x01(\tR\aprofile\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12$\n" +
	"\x0eavatar_file_id\x18\a \x01(\tR\favatarFileId\x12\x10\n" +
	"\x03age\x18\b \x01(\x05R\x03age\x12\x14\n" +
	"\x05intro\x18\t \x01(\tR\x05intro\x12)\n" +
	"\x06custom\x18\n" +
	" \x03(\v2\x11.profile.PropertyR\x06custom\"C\n" +
	"\x15UpdateProfileResponse\x12*\n" +
	"\aprofile\x18\x01 \x01(\v2\x10.profile.ProfileR\aprofile\"&\n" +
	"\x14DeleteProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteProfileResponse2\x8d\x05\n" +
	"\x0eProfileService\x12t\n" +
	"\n" +
	"GetProfile\x12\x1a.profile.GetProfileRequest\x1a\x1b.profile.GetProfileResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/profile.ProfileService/GetProfile\x12|\n" +
	"\fListProfiles\x12\x1c.profile.ListProfilesRequest\x1a\x1d.profile.ListProfilesResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/profile.ProfileService/ListProfiles\x12\x80\x01\n" +
	"\rCreateProfile\x12\x1d.profile.CreateProfileRequest\x1a\x1e.profile.CreateProfileResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/profile.ProfileService/CreateProfile\x12\x80\x01\n" +
	"\rUpdateProfile\x12\x1d.profile.UpdateProfileRequest\x1a\x1e.profile.UpdateProfileResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/profile.ProfileService/UpdateProfile\x12\x80\x01\n" +
	"\rDeleteProfile\x12\x1d.profile.DeleteProfileRequest\x1a\x1e.profile.DeleteProfileResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/profile.ProfileService/DeleteProfileB\x1aZ\x18app_server/proto/profileb\x06proto3"

var (
	file_proto_profile_profile_proto_rawDescOnce sync.Once
	file_proto_profile_profile_proto_rawDescData []byte
)

func file_proto_profile_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)))
	})
	return file_proto_profile_profile_proto_rawDescData
}

var file_proto_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_profile_profile_proto_goTypes = []any{
	(*Property)(nil),              // 0: profile.Property
	(*Profile)(nil),               // 1: profile.Profile
	(*GetProfileRequest)(nil),     // 2: profile.GetProfileRequest
	(*GetProfileResponse)(nil),    // 3: profile.GetProfileResponse
	(*ListProfilesRequest)(nil),   // 4: profile.ListProfilesRequest
	(*ListProfilesResponse)(nil),  // 5: profile.ListProfilesResponse
	(*CreateProfileRequest)(nil),  // 6: profile.CreateProfileRequest
	(*CreateProfileResponse)(nil), // 7: profile.CreateProfileResponse
	(*UpdateProfileRequest)(nil),  // 8: profile.UpdateProfileRequest
	(*UpdateProfileResponse)(nil), // 9: profile.UpdateProfileResponse
	(*DeleteProfileRequest)(nil),  // 10: profile.DeleteProfileRequest
	(*DeleteProfileResponse)(nil), // 11: profile.DeleteProfileResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_profile_profile_proto_depIdxs = []int32{
	12, // 0: profile.Profile.birthday:type_name -> google.protobuf.Timestamp
	12, // 1: profile.Profile.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: profile.Profile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: profile.Profile.custom:type_name -> profile.Property
	1,  // 4: profile.GetProfileResponse.profile:type_name -> profile.Profile
	1,  // 5: profile.ListProfilesResponse.profiles:type_name -> profile.Profile
	0,  // 6: profile.CreateProfileRequest.custom:type_name -> profile.Property
	1,  // 7: profile.CreateProfileResponse.profile:type_name -> profile.Profile
	0,  // 8: profile.UpdateProfileRequest.custom:type_name -> profile.Property
	1,  // 9: profile.UpdateProfileResponse.profile:type_name -> profile.Profile
	2,  // 10: profile.ProfileService.GetProfile:input_type -> profile.GetProfileRequest
	4,  // 11: profile.ProfileService.ListProfiles:input_type -> profile.ListProfilesRequest
	6,  // 12: profile.ProfileService.CreateProfile:input_type -> profile.CreateProfileRequest
	8,  // 13: profile.ProfileService.UpdateProfile:input_type -> profile.UpdateProfileRequest
	10, // 14: profile.ProfileService.DeleteProfile:input_type -> profile.DeleteProfileRequest
	3,  // 15: profile.ProfileService.GetProfile:output_type -> profile.GetProfileResponse
	5,  // 16: profile.ProfileService.ListProfiles:output_type -> profile.ListProfilesResponse
	7,  // 17: profile.ProfileService.CreateProfile:output_type -> profile.CreateProfileResponse
	9,  // 18: profile.ProfileService.UpdateProfile:output_type -> profile.UpdateProfileResponse
	11, // 19: profile.ProfileService.DeleteProfile:output_type -> profile.DeleteProfileResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_profile_profile_proto_init() }
func file_proto_profile_profile_proto_init() {
	if File_proto_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_profile_proto_rawDesc), len(file_proto_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_profile_proto = out.File
	file_proto_profile_profile_proto_goTypes = nil
	file_proto_profile_profile_proto_depIdxs = nil
}
