// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/config/config.proto

package config

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proto_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Config) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	App           string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Env           string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_proto_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetConfigRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *GetConfigRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetConfigRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *GetConfigRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*Config              `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_proto_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigResponse) GetConfigs() []*Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

var File_proto_config_config_proto protoreflect.FileDescriptor

const file_proto_config_config_proto_rawDesc = "" +
	"\n" +
	"\x19proto/config/config.proto\x12\x06config\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x06Config\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x80\x01\n" +
	"\x10GetConfigRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"=\n" +
	"\x11GetConfigResponse\x12(\n" +
	"\aconfigs\x18\x01 \x03(\v2\x0e.config.ConfigR\aconfigs2}\n" +
	"\rConfigService\x12l\n" +
	"\tGetConfig\x12\x18.config.GetConfigRequest\x1a\x19.config.GetConfigResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/config.ConfigService/GetConfigB\x19Z\x17app_server/proto/configb\x06proto3"

var (
	file_proto_config_config_proto_rawDescOnce sync.Once
	file_proto_config_config_proto_rawDescData []byte
)

func file_proto_config_config_proto_rawDescGZIP() []byte {
	file_proto_config_config_proto_rawDescOnce.Do(func() {
		file_proto_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_config_proto_rawDesc), len(file_proto_config_config_proto_rawDesc)))
	})
	return file_proto_config_config_proto_rawDescData
}

var file_proto_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_config_config_proto_goTypes = []any{
	(*Config)(nil),            // 0: config.Config
	(*GetConfigRequest)(nil),  // 1: config.GetConfigRequest
	(*GetConfigResponse)(nil), // 2: config.GetConfigResponse
}
var file_proto_config_config_proto_depIdxs = []int32{
	0, // 0: config.GetConfigResponse.configs:type_name -> config.Config
	1, // 1: config.ConfigService.GetConfig:input_type -> config.GetConfigRequest
	2, // 2: config.ConfigService.GetConfig:output_type -> config.GetConfigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_config_config_proto_init() }
func file_proto_config_config_proto_init() {
	if File_proto_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_config_proto_rawDesc), len(file_proto_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_config_proto_goTypes,
		DependencyIndexes: file_proto_config_config_proto_depIdxs,
		MessageInfos:      file_proto_config_config_proto_msgTypes,
	}.Build()
	File_proto_config_config_proto = out.File
	file_proto_config_config_proto_goTypes = nil
	file_proto_config_config_proto_depIdxs = nil
}
