// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/chat/chat.proto

package chat

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 聊天会话ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户ID
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 个人资料ID
	ProfileId string `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	// 名称
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// 头像
	Avatar string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSession) Reset() {
	*x = ChatSession{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSession) ProtoMessage() {}

func (x *ChatSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSession.ProtoReflect.Descriptor instead.
func (*ChatSession) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatSession) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatSession) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ChatSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatSession) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ChatSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListChatSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页
	PageToken string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// 每页大小
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsRequest) Reset() {
	*x = ListChatSessionsRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsRequest) ProtoMessage() {}

func (x *ListChatSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListChatSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ListChatSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListChatSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListChatSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []*ChatSession         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// 下一页
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatSessionsResponse) Reset() {
	*x = ListChatSessionsResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatSessionsResponse) ProtoMessage() {}

func (x *ListChatSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListChatSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ListChatSessionsResponse) GetData() []*ChatSession {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListChatSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateChatSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 头像
	Avatar string `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 个人资料信息 创建对话时 快速创建个人资料
	Profile       *ProfileShort `protobuf:"bytes,3,opt,name=profile,proto3,oneof" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatSessionRequest) Reset() {
	*x = CreateChatSessionRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionRequest) ProtoMessage() {}

func (x *CreateChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChatSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatSessionRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateChatSessionRequest) GetProfile() *ProfileShort {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ProfileShort struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 个人资料名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 个人资料IM名称
	ImName *string `protobuf:"bytes,2,opt,name=im_name,json=imName,proto3,oneof" json:"im_name,omitempty"`
	// 个人资料头像
	Avatar *string `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	// 个人资料性别
	Gender *string `protobuf:"bytes,4,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	// 个人资料生日
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileShort) Reset() {
	*x = ProfileShort{}
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileShort) ProtoMessage() {}

func (x *ProfileShort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileShort.ProtoReflect.Descriptor instead.
func (*ProfileShort) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileShort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileShort) GetImName() string {
	if x != nil && x.ImName != nil {
		return *x.ImName
	}
	return ""
}

func (x *ProfileShort) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *ProfileShort) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *ProfileShort) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

type CreateChatSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 聊天会话
	ChatSession   *ChatSession `protobuf:"bytes,1,opt,name=chat_session,json=chatSession,proto3" json:"chat_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatSessionResponse) Reset() {
	*x = CreateChatSessionResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatSessionResponse) ProtoMessage() {}

func (x *CreateChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *CreateChatSessionResponse) GetChatSession() *ChatSession {
	if x != nil {
		return x.ChatSession
	}
	return nil
}

type DeleteChatSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 聊天会话ID
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatSessionRequest) Reset() {
	*x = DeleteChatSessionRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatSessionRequest) ProtoMessage() {}

func (x *DeleteChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteChatSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteChatSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatSessionResponse) Reset() {
	*x = DeleteChatSessionResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatSessionResponse) ProtoMessage() {}

func (x *DeleteChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{7}
}

type UpdateChatSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 聊天会话ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 头像
	Avatar        string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatSessionRequest) Reset() {
	*x = UpdateChatSessionRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatSessionRequest) ProtoMessage() {}

func (x *UpdateChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateChatSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChatSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateChatSessionRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateChatSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatSession   *ChatSession           `protobuf:"bytes,1,opt,name=chat_session,json=chatSession,proto3" json:"chat_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatSessionResponse) Reset() {
	*x = UpdateChatSessionResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatSessionResponse) ProtoMessage() {}

func (x *UpdateChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateChatSessionResponse) GetChatSession() *ChatSession {
	if x != nil {
		return x.ChatSession
	}
	return nil
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xf7\x01\n" +
	"\vChatSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"U\n" +
	"\x17ListChatSessionsRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"i\n" +
	"\x18ListChatSessionsResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.chat.ChatSessionR\x04data\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x85\x01\n" +
	"\x18CreateChatSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x121\n" +
	"\aprofile\x18\x03 \x01(\v2\x12.chat.ProfileShortH\x00R\aprofile\x88\x01\x01B\n" +
	"\n" +
	"\b_profile\"\xe6\x01\n" +
	"\fProfileShort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\aim_name\x18\x02 \x01(\tH\x00R\x06imName\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x01R\x06avatar\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x04 \x01(\tH\x02R\x06gender\x88\x01\x01\x12;\n" +
	"\bbirthday\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\bbirthday\x88\x01\x01B\n" +
	"\n" +
	"\b_im_nameB\t\n" +
	"\a_avatarB\t\n" +
	"\a_genderB\v\n" +
	"\t_birthday\"Q\n" +
	"\x19CreateChatSessionResponse\x124\n" +
	"\fchat_session\x18\x01 \x01(\v2\x11.chat.ChatSessionR\vchatSession\"*\n" +
	"\x18DeleteChatSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteChatSessionResponse\"V\n" +
	"\x18UpdateChatSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"Q\n" +
	"\x19UpdateChatSessionResponse\x124\n" +
	"\fchat_session\x18\x01 \x01(\v2\x11.chat.ChatSessionR\vchatSession2\xa5\x04\n" +
	"\vChatService\x12\x80\x01\n" +
	"\x10ListChatSessions\x12\x1d.chat.ListChatSessionsRequest\x1a\x1e.chat.ListChatSessionsResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/chat.ChatService/ListChatSessions\x12\x84\x01\n" +
	"\x11CreateChatSession\x12\x1e.chat.CreateChatSessionRequest\x1a\x1f.chat.CreateChatSessionResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/chat.ChatService/CreateChatSession\x12\x84\x01\n" +
	"\x11DeleteChatSession\x12\x1e.chat.DeleteChatSessionRequest\x1a\x1f.chat.DeleteChatSessionResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/chat.ChatService/DeleteChatSession\x12\x84\x01\n" +
	"\x11UpdateChatSession\x12\x1e.chat.UpdateChatSessionRequest\x1a\x1f.chat.UpdateChatSessionResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/chat.ChatService/UpdateChatSessionB\x17Z\x15app_server/proto/chatb\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_chat_chat_proto_goTypes = []any{
	(*ChatSession)(nil),               // 0: chat.ChatSession
	(*ListChatSessionsRequest)(nil),   // 1: chat.ListChatSessionsRequest
	(*ListChatSessionsResponse)(nil),  // 2: chat.ListChatSessionsResponse
	(*CreateChatSessionRequest)(nil),  // 3: chat.CreateChatSessionRequest
	(*ProfileShort)(nil),              // 4: chat.ProfileShort
	(*CreateChatSessionResponse)(nil), // 5: chat.CreateChatSessionResponse
	(*DeleteChatSessionRequest)(nil),  // 6: chat.DeleteChatSessionRequest
	(*DeleteChatSessionResponse)(nil), // 7: chat.DeleteChatSessionResponse
	(*UpdateChatSessionRequest)(nil),  // 8: chat.UpdateChatSessionRequest
	(*UpdateChatSessionResponse)(nil), // 9: chat.UpdateChatSessionResponse
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	10, // 0: chat.ChatSession.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: chat.ChatSession.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: chat.ListChatSessionsResponse.data:type_name -> chat.ChatSession
	4,  // 3: chat.CreateChatSessionRequest.profile:type_name -> chat.ProfileShort
	10, // 4: chat.ProfileShort.birthday:type_name -> google.protobuf.Timestamp
	0,  // 5: chat.CreateChatSessionResponse.chat_session:type_name -> chat.ChatSession
	0,  // 6: chat.UpdateChatSessionResponse.chat_session:type_name -> chat.ChatSession
	1,  // 7: chat.ChatService.ListChatSessions:input_type -> chat.ListChatSessionsRequest
	3,  // 8: chat.ChatService.CreateChatSession:input_type -> chat.CreateChatSessionRequest
	6,  // 9: chat.ChatService.DeleteChatSession:input_type -> chat.DeleteChatSessionRequest
	8,  // 10: chat.ChatService.UpdateChatSession:input_type -> chat.UpdateChatSessionRequest
	2,  // 11: chat.ChatService.ListChatSessions:output_type -> chat.ListChatSessionsResponse
	5,  // 12: chat.ChatService.CreateChatSession:output_type -> chat.CreateChatSessionResponse
	7,  // 13: chat.ChatService.DeleteChatSession:output_type -> chat.DeleteChatSessionResponse
	9,  // 14: chat.ChatService.UpdateChatSession:output_type -> chat.UpdateChatSessionResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	file_proto_chat_chat_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_chat_chat_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
