// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/user/user.proto

package userconnect

import (
	user "app_server/proto/user"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "user.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceWxUserLoginProcedure is the fully-qualified name of the UserService's WxUserLogin RPC.
	UserServiceWxUserLoginProcedure = "/user.UserService/WxUserLogin"
	// UserServicePhoneLoginProcedure is the fully-qualified name of the UserService's PhoneLogin RPC.
	UserServicePhoneLoginProcedure = "/user.UserService/PhoneLogin"
	// UserServiceGetUserProfileProcedure is the fully-qualified name of the UserService's
	// GetUserProfile RPC.
	UserServiceGetUserProfileProcedure = "/user.UserService/GetUserProfile"
)

// UserServiceClient is a client for the user.UserService service.
type UserServiceClient interface {
	// POST /user.UserService/WxUserLogin
	WxUserLogin(context.Context, *connect.Request[user.WxUserLoginRequest]) (*connect.Response[user.WxUserLoginResponse], error)
	// POST /user.UserService/PhoneLogin
	PhoneLogin(context.Context, *connect.Request[user.PhoneLoginRequest]) (*connect.Response[user.PhoneLoginResponse], error)
	// POST /user.UserService/GetUserProfile
	GetUserProfile(context.Context, *connect.Request[user.GetUserProfileRequest]) (*connect.Response[user.GetUserProfileResponse], error)
}

// NewUserServiceClient constructs a client for the user.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := user.File_proto_user_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		wxUserLogin: connect.NewClient[user.WxUserLoginRequest, user.WxUserLoginResponse](
			httpClient,
			baseURL+UserServiceWxUserLoginProcedure,
			connect.WithSchema(userServiceMethods.ByName("WxUserLogin")),
			connect.WithClientOptions(opts...),
		),
		phoneLogin: connect.NewClient[user.PhoneLoginRequest, user.PhoneLoginResponse](
			httpClient,
			baseURL+UserServicePhoneLoginProcedure,
			connect.WithSchema(userServiceMethods.ByName("PhoneLogin")),
			connect.WithClientOptions(opts...),
		),
		getUserProfile: connect.NewClient[user.GetUserProfileRequest, user.GetUserProfileResponse](
			httpClient,
			baseURL+UserServiceGetUserProfileProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUserProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	wxUserLogin    *connect.Client[user.WxUserLoginRequest, user.WxUserLoginResponse]
	phoneLogin     *connect.Client[user.PhoneLoginRequest, user.PhoneLoginResponse]
	getUserProfile *connect.Client[user.GetUserProfileRequest, user.GetUserProfileResponse]
}

// WxUserLogin calls user.UserService.WxUserLogin.
func (c *userServiceClient) WxUserLogin(ctx context.Context, req *connect.Request[user.WxUserLoginRequest]) (*connect.Response[user.WxUserLoginResponse], error) {
	return c.wxUserLogin.CallUnary(ctx, req)
}

// PhoneLogin calls user.UserService.PhoneLogin.
func (c *userServiceClient) PhoneLogin(ctx context.Context, req *connect.Request[user.PhoneLoginRequest]) (*connect.Response[user.PhoneLoginResponse], error) {
	return c.phoneLogin.CallUnary(ctx, req)
}

// GetUserProfile calls user.UserService.GetUserProfile.
func (c *userServiceClient) GetUserProfile(ctx context.Context, req *connect.Request[user.GetUserProfileRequest]) (*connect.Response[user.GetUserProfileResponse], error) {
	return c.getUserProfile.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the user.UserService service.
type UserServiceHandler interface {
	// POST /user.UserService/WxUserLogin
	WxUserLogin(context.Context, *connect.Request[user.WxUserLoginRequest]) (*connect.Response[user.WxUserLoginResponse], error)
	// POST /user.UserService/PhoneLogin
	PhoneLogin(context.Context, *connect.Request[user.PhoneLoginRequest]) (*connect.Response[user.PhoneLoginResponse], error)
	// POST /user.UserService/GetUserProfile
	GetUserProfile(context.Context, *connect.Request[user.GetUserProfileRequest]) (*connect.Response[user.GetUserProfileResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := user.File_proto_user_user_proto.Services().ByName("UserService").Methods()
	userServiceWxUserLoginHandler := connect.NewUnaryHandler(
		UserServiceWxUserLoginProcedure,
		svc.WxUserLogin,
		connect.WithSchema(userServiceMethods.ByName("WxUserLogin")),
		connect.WithHandlerOptions(opts...),
	)
	userServicePhoneLoginHandler := connect.NewUnaryHandler(
		UserServicePhoneLoginProcedure,
		svc.PhoneLogin,
		connect.WithSchema(userServiceMethods.ByName("PhoneLogin")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetUserProfileHandler := connect.NewUnaryHandler(
		UserServiceGetUserProfileProcedure,
		svc.GetUserProfile,
		connect.WithSchema(userServiceMethods.ByName("GetUserProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceWxUserLoginProcedure:
			userServiceWxUserLoginHandler.ServeHTTP(w, r)
		case UserServicePhoneLoginProcedure:
			userServicePhoneLoginHandler.ServeHTTP(w, r)
		case UserServiceGetUserProfileProcedure:
			userServiceGetUserProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) WxUserLogin(context.Context, *connect.Request[user.WxUserLoginRequest]) (*connect.Response[user.WxUserLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.UserService.WxUserLogin is not implemented"))
}

func (UnimplementedUserServiceHandler) PhoneLogin(context.Context, *connect.Request[user.PhoneLoginRequest]) (*connect.Response[user.PhoneLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.UserService.PhoneLogin is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUserProfile(context.Context, *connect.Request[user.GetUserProfileRequest]) (*connect.Response[user.GetUserProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.UserService.GetUserProfile is not implemented"))
}
