// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/translate/translate.proto

package translateconnect

import (
	translate "app_server/proto/translate"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TranslateServiceName is the fully-qualified name of the TranslateService service.
	TranslateServiceName = "translate.TranslateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TranslateServiceTranslateProcedure is the fully-qualified name of the TranslateService's
	// Translate RPC.
	TranslateServiceTranslateProcedure = "/translate.TranslateService/Translate"
	// TranslateServiceTranslateFriendMessageProcedure is the fully-qualified name of the
	// TranslateService's TranslateFriendMessage RPC.
	TranslateServiceTranslateFriendMessageProcedure = "/translate.TranslateService/TranslateFriendMessage"
	// TranslateServiceTranslateV2Procedure is the fully-qualified name of the TranslateService's
	// TranslateV2 RPC.
	TranslateServiceTranslateV2Procedure = "/translate.TranslateService/TranslateV2"
)

// TranslateServiceClient is a client for the translate.TranslateService service.
type TranslateServiceClient interface {
	Translate(context.Context, *connect.Request[translate.TranslateRequest]) (*connect.Response[translate.TranslateResponse], error)
	TranslateFriendMessage(context.Context, *connect.Request[translate.TranslateFriendMessageRequest]) (*connect.Response[translate.TranslateFriendMessageResponse], error)
	TranslateV2(context.Context, *connect.Request[translate.TranslateV2Request]) (*connect.Response[translate.TranslateV2Response], error)
}

// NewTranslateServiceClient constructs a client for the translate.TranslateService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTranslateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TranslateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	translateServiceMethods := translate.File_proto_translate_translate_proto.Services().ByName("TranslateService").Methods()
	return &translateServiceClient{
		translate: connect.NewClient[translate.TranslateRequest, translate.TranslateResponse](
			httpClient,
			baseURL+TranslateServiceTranslateProcedure,
			connect.WithSchema(translateServiceMethods.ByName("Translate")),
			connect.WithClientOptions(opts...),
		),
		translateFriendMessage: connect.NewClient[translate.TranslateFriendMessageRequest, translate.TranslateFriendMessageResponse](
			httpClient,
			baseURL+TranslateServiceTranslateFriendMessageProcedure,
			connect.WithSchema(translateServiceMethods.ByName("TranslateFriendMessage")),
			connect.WithClientOptions(opts...),
		),
		translateV2: connect.NewClient[translate.TranslateV2Request, translate.TranslateV2Response](
			httpClient,
			baseURL+TranslateServiceTranslateV2Procedure,
			connect.WithSchema(translateServiceMethods.ByName("TranslateV2")),
			connect.WithClientOptions(opts...),
		),
	}
}

// translateServiceClient implements TranslateServiceClient.
type translateServiceClient struct {
	translate              *connect.Client[translate.TranslateRequest, translate.TranslateResponse]
	translateFriendMessage *connect.Client[translate.TranslateFriendMessageRequest, translate.TranslateFriendMessageResponse]
	translateV2            *connect.Client[translate.TranslateV2Request, translate.TranslateV2Response]
}

// Translate calls translate.TranslateService.Translate.
func (c *translateServiceClient) Translate(ctx context.Context, req *connect.Request[translate.TranslateRequest]) (*connect.Response[translate.TranslateResponse], error) {
	return c.translate.CallUnary(ctx, req)
}

// TranslateFriendMessage calls translate.TranslateService.TranslateFriendMessage.
func (c *translateServiceClient) TranslateFriendMessage(ctx context.Context, req *connect.Request[translate.TranslateFriendMessageRequest]) (*connect.Response[translate.TranslateFriendMessageResponse], error) {
	return c.translateFriendMessage.CallUnary(ctx, req)
}

// TranslateV2 calls translate.TranslateService.TranslateV2.
func (c *translateServiceClient) TranslateV2(ctx context.Context, req *connect.Request[translate.TranslateV2Request]) (*connect.Response[translate.TranslateV2Response], error) {
	return c.translateV2.CallUnary(ctx, req)
}

// TranslateServiceHandler is an implementation of the translate.TranslateService service.
type TranslateServiceHandler interface {
	Translate(context.Context, *connect.Request[translate.TranslateRequest]) (*connect.Response[translate.TranslateResponse], error)
	TranslateFriendMessage(context.Context, *connect.Request[translate.TranslateFriendMessageRequest]) (*connect.Response[translate.TranslateFriendMessageResponse], error)
	TranslateV2(context.Context, *connect.Request[translate.TranslateV2Request]) (*connect.Response[translate.TranslateV2Response], error)
}

// NewTranslateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTranslateServiceHandler(svc TranslateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	translateServiceMethods := translate.File_proto_translate_translate_proto.Services().ByName("TranslateService").Methods()
	translateServiceTranslateHandler := connect.NewUnaryHandler(
		TranslateServiceTranslateProcedure,
		svc.Translate,
		connect.WithSchema(translateServiceMethods.ByName("Translate")),
		connect.WithHandlerOptions(opts...),
	)
	translateServiceTranslateFriendMessageHandler := connect.NewUnaryHandler(
		TranslateServiceTranslateFriendMessageProcedure,
		svc.TranslateFriendMessage,
		connect.WithSchema(translateServiceMethods.ByName("TranslateFriendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	translateServiceTranslateV2Handler := connect.NewUnaryHandler(
		TranslateServiceTranslateV2Procedure,
		svc.TranslateV2,
		connect.WithSchema(translateServiceMethods.ByName("TranslateV2")),
		connect.WithHandlerOptions(opts...),
	)
	return "/translate.TranslateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TranslateServiceTranslateProcedure:
			translateServiceTranslateHandler.ServeHTTP(w, r)
		case TranslateServiceTranslateFriendMessageProcedure:
			translateServiceTranslateFriendMessageHandler.ServeHTTP(w, r)
		case TranslateServiceTranslateV2Procedure:
			translateServiceTranslateV2Handler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTranslateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTranslateServiceHandler struct{}

func (UnimplementedTranslateServiceHandler) Translate(context.Context, *connect.Request[translate.TranslateRequest]) (*connect.Response[translate.TranslateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("translate.TranslateService.Translate is not implemented"))
}

func (UnimplementedTranslateServiceHandler) TranslateFriendMessage(context.Context, *connect.Request[translate.TranslateFriendMessageRequest]) (*connect.Response[translate.TranslateFriendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("translate.TranslateService.TranslateFriendMessage is not implemented"))
}

func (UnimplementedTranslateServiceHandler) TranslateV2(context.Context, *connect.Request[translate.TranslateV2Request]) (*connect.Response[translate.TranslateV2Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("translate.TranslateService.TranslateV2 is not implemented"))
}
