// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/message/message.proto

package message

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatMessage 统一的消息实体，移除了 profile_id
type ChatMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParentId         string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Role             string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                      // SELF, FRIEND, USER, AI.
	MsgType          string                 `protobuf:"bytes,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"` // HISTORY, CONSULT, TRANSLATE.
	Content          string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Tags             []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	MsgAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=msg_at,json=msgAt,proto3" json:"msg_at,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TranslateContent *string                `protobuf:"bytes,12,opt,name=translate_content,json=translateContent,proto3,oneof" json:"translate_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ChatMessage) GetMsgAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MsgAt
	}
	return nil
}

func (x *ChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ChatMessage) GetTranslateContent() string {
	if x != nil && x.TranslateContent != nil {
		return *x.TranslateContent
	}
	return ""
}

// 查询消息请求 - 支持多种过滤条件
type ListChatMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 过滤条件
	SessionId string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 按会话ID过滤（必填）
	MsgType   string   `protobuf:"bytes,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`       // 按消息类型过滤（可选）
	Roles     []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`                          // 按角色过滤（可选）
	Ids       []string `protobuf:"bytes,4,rep,name=ids,proto3" json:"ids,omitempty"`                              // 按ID列表过滤（可选）
	ParentIds []string `protobuf:"bytes,5,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"` // 按父消息ID过滤（可选）
	// 分页参数
	PageSize      int32  `protobuf:"varint,21,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,22,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessagesRequest) Reset() {
	*x = ListChatMessagesRequest{}
	mi := &file_proto_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesRequest) ProtoMessage() {}

func (x *ListChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *ListChatMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListChatMessagesRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *ListChatMessagesRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListChatMessagesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListChatMessagesRequest) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *ListChatMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListChatMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListChatMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessagesResponse) Reset() {
	*x = ListChatMessagesResponse{}
	mi := &file_proto_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesResponse) ProtoMessage() {}

func (x *ListChatMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListChatMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *ListChatMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListChatMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// 创建消息请求
type CreateChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatMessageRequest) Reset() {
	*x = CreateChatMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageRequest) ProtoMessage() {}

func (x *CreateChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChatMessageRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CreateChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatMessageResponse) Reset() {
	*x = CreateChatMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatMessageResponse) ProtoMessage() {}

func (x *CreateChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *CreateChatMessageResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 更新消息请求
type UpdateChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatMessageRequest) Reset() {
	*x = UpdateChatMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatMessageRequest) ProtoMessage() {}

func (x *UpdateChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateChatMessageRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type UpdateChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatMessageResponse) Reset() {
	*x = UpdateChatMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatMessageResponse) ProtoMessage() {}

func (x *UpdateChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatMessageResponse.ProtoReflect.Descriptor instead.
func (*UpdateChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateChatMessageResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 删除消息请求
type DeleteChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatMessageRequest) Reset() {
	*x = DeleteChatMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatMessageRequest) ProtoMessage() {}

func (x *DeleteChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChatMessageRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // 返回删除的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatMessageResponse) Reset() {
	*x = DeleteChatMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatMessageResponse) ProtoMessage() {}

func (x *DeleteChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChatMessageResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// 发送咨询消息请求
type SendConsultMessageRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	Content   string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                      // 咨询内容
	// optional string mention_id = 3;      // 提及消息ID
	TargetId      *string `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"` // 目标消息ID regenerate时使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConsultMessageRequest) Reset() {
	*x = SendConsultMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConsultMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConsultMessageRequest) ProtoMessage() {}

func (x *SendConsultMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConsultMessageRequest.ProtoReflect.Descriptor instead.
func (*SendConsultMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{9}
}

func (x *SendConsultMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendConsultMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendConsultMessageRequest) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

type SendConsultMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consult       *ChatMessage           `protobuf:"bytes,1,opt,name=consult,proto3" json:"consult,omitempty"` // 创建的咨询消息
	Reply         *ChatMessage           `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`     // 回复的消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConsultMessageResponse) Reset() {
	*x = SendConsultMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConsultMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConsultMessageResponse) ProtoMessage() {}

func (x *SendConsultMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConsultMessageResponse.ProtoReflect.Descriptor instead.
func (*SendConsultMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{10}
}

func (x *SendConsultMessageResponse) GetConsult() *ChatMessage {
	if x != nil {
		return x.Consult
	}
	return nil
}

func (x *SendConsultMessageResponse) GetReply() *ChatMessage {
	if x != nil {
		return x.Reply
	}
	return nil
}

// 解析图片消息请求（保持不变）
type ParseImageMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 改为 session_id，不再需要 profile_id
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseImageMessagesRequest) Reset() {
	*x = ParseImageMessagesRequest{}
	mi := &file_proto_message_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseImageMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseImageMessagesRequest) ProtoMessage() {}

func (x *ParseImageMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseImageMessagesRequest.ProtoReflect.Descriptor instead.
func (*ParseImageMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{11}
}

func (x *ParseImageMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ParseImageMessagesRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ParseImageMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseImageMessagesResponse) Reset() {
	*x = ParseImageMessagesResponse{}
	mi := &file_proto_message_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseImageMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseImageMessagesResponse) ProtoMessage() {}

func (x *ParseImageMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseImageMessagesResponse.ProtoReflect.Descriptor instead.
func (*ParseImageMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{12}
}

func (x *ParseImageMessagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseImageMessagesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ParseImageMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 用户反馈 点赞/踩/评论
type FeedbackToMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 消息ID
	Attitude      string                 `protobuf:"bytes,3,opt,name=attitude,proto3" json:"attitude,omitempty"`                    // 态度: up, down
	Feedback      string                 `protobuf:"bytes,4,opt,name=feedback,proto3" json:"feedback,omitempty"`                    // 文字反馈内容
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                            // 标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackToMessageRequest) Reset() {
	*x = FeedbackToMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackToMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackToMessageRequest) ProtoMessage() {}

func (x *FeedbackToMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackToMessageRequest.ProtoReflect.Descriptor instead.
func (*FeedbackToMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{13}
}

func (x *FeedbackToMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FeedbackToMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *FeedbackToMessageRequest) GetAttitude() string {
	if x != nil {
		return x.Attitude
	}
	return ""
}

func (x *FeedbackToMessageRequest) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *FeedbackToMessageRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type FeedbackToMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackToMessageResponse) Reset() {
	*x = FeedbackToMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackToMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackToMessageResponse) ProtoMessage() {}

func (x *FeedbackToMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackToMessageResponse.ProtoReflect.Descriptor instead.
func (*FeedbackToMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{14}
}

func (x *FeedbackToMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 保留旧的消息类型定义以向后兼容
//
// Deprecated: Marked as deprecated in proto/message/message.proto.
type ConsultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,5,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	MsgType       string                 `protobuf:"bytes,7,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	MsgAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=msg_at,json=msgAt,proto3" json:"msg_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultMessage) Reset() {
	*x = ConsultMessage{}
	mi := &file_proto_message_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultMessage) ProtoMessage() {}

func (x *ConsultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultMessage.ProtoReflect.Descriptor instead.
func (*ConsultMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{15}
}

func (x *ConsultMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsultMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsultMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsultMessage) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ConsultMessage) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ConsultMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConsultMessage) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *ConsultMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConsultMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ConsultMessage) GetMsgAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MsgAt
	}
	return nil
}

func (x *ConsultMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConsultMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 保留旧的请求/响应消息以向后兼容
//
// Deprecated: Marked as deprecated in proto/message/message.proto.
type ListConsultMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       string                 `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Ids           []string               `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	SessionIds    []string               `protobuf:"bytes,3,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	ParentIds     []string               `protobuf:"bytes,4,rep,name=parent_ids,json=parentIds,proto3" json:"parent_ids,omitempty"`
	PageSize      int32                  `protobuf:"varint,21,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,22,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsultMessagesRequest) Reset() {
	*x = ListConsultMessagesRequest{}
	mi := &file_proto_message_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsultMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsultMessagesRequest) ProtoMessage() {}

func (x *ListConsultMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsultMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListConsultMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{16}
}

func (x *ListConsultMessagesRequest) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *ListConsultMessagesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListConsultMessagesRequest) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *ListConsultMessagesRequest) GetParentIds() []string {
	if x != nil {
		return x.ParentIds
	}
	return nil
}

func (x *ListConsultMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListConsultMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type ListConsultMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsultMessagesResponse) Reset() {
	*x = ListConsultMessagesResponse{}
	mi := &file_proto_message_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsultMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsultMessagesResponse) ProtoMessage() {}

func (x *ListConsultMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsultMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListConsultMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{17}
}

func (x *ListConsultMessagesResponse) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListConsultMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type UpdateConsultMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConsultMessageRequest) Reset() {
	*x = UpdateConsultMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConsultMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsultMessageRequest) ProtoMessage() {}

func (x *UpdateConsultMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsultMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateConsultMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateConsultMessageRequest) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type UpdateConsultMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConsultMessageResponse) Reset() {
	*x = UpdateConsultMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConsultMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsultMessageResponse) ProtoMessage() {}

func (x *UpdateConsultMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsultMessageResponse.ProtoReflect.Descriptor instead.
func (*UpdateConsultMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateConsultMessageResponse) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type RecallConsultMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallConsultMessageRequest) Reset() {
	*x = RecallConsultMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallConsultMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallConsultMessageRequest) ProtoMessage() {}

func (x *RecallConsultMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallConsultMessageRequest.ProtoReflect.Descriptor instead.
func (*RecallConsultMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{20}
}

func (x *RecallConsultMessageRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type RecallConsultMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallConsultMessageResponse) Reset() {
	*x = RecallConsultMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallConsultMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallConsultMessageResponse) ProtoMessage() {}

func (x *RecallConsultMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallConsultMessageResponse.ProtoReflect.Descriptor instead.
func (*RecallConsultMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{21}
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type ListFriendMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,21,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,22,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendMessagesRequest) Reset() {
	*x = ListFriendMessagesRequest{}
	mi := &file_proto_message_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendMessagesRequest) ProtoMessage() {}

func (x *ListFriendMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListFriendMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{22}
}

func (x *ListFriendMessagesRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ListFriendMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFriendMessagesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type ListFriendMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendMessagesResponse) Reset() {
	*x = ListFriendMessagesResponse{}
	mi := &file_proto_message_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendMessagesResponse) ProtoMessage() {}

func (x *ListFriendMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListFriendMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{23}
}

func (x *ListFriendMessagesResponse) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListFriendMessagesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type CreateFriendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFriendMessageRequest) Reset() {
	*x = CreateFriendMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFriendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFriendMessageRequest) ProtoMessage() {}

func (x *CreateFriendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFriendMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateFriendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{24}
}

func (x *CreateFriendMessageRequest) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type CreateFriendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFriendMessageResponse) Reset() {
	*x = CreateFriendMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFriendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFriendMessageResponse) ProtoMessage() {}

func (x *CreateFriendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFriendMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateFriendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{25}
}

func (x *CreateFriendMessageResponse) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type UpdateFriendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendMessageRequest) Reset() {
	*x = UpdateFriendMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendMessageRequest) ProtoMessage() {}

func (x *UpdateFriendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateFriendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateFriendMessageRequest) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type UpdateFriendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ConsultMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFriendMessageResponse) Reset() {
	*x = UpdateFriendMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFriendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFriendMessageResponse) ProtoMessage() {}

func (x *UpdateFriendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFriendMessageResponse.ProtoReflect.Descriptor instead.
func (*UpdateFriendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateFriendMessageResponse) GetMessages() []*ConsultMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type DeleteFriendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendMessageRequest) Reset() {
	*x = DeleteFriendMessageRequest{}
	mi := &file_proto_message_message_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendMessageRequest) ProtoMessage() {}

func (x *DeleteFriendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteFriendMessageRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// Deprecated: Marked as deprecated in proto/message/message.proto.
type DeleteFriendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendMessageResponse) Reset() {
	*x = DeleteFriendMessageResponse{}
	mi := &file_proto_message_message_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendMessageResponse) ProtoMessage() {}

func (x *DeleteFriendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_message_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteFriendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_message_proto_rawDescGZIP(), []int{29}
}

var File_proto_message_message_proto protoreflect.FileDescriptor

const file_proto_message_message_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/message/message.proto\x12\amessage\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xc0\x03\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x19\n" +
	"\bmsg_type\x18\x06 \x01(\tR\amsgType\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x121\n" +
	"\x06msg_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x05msgAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x120\n" +
	"\x11translate_content\x18\f \x01(\tH\x00R\x10translateContent\x88\x01\x01B\x14\n" +
	"\x12_translate_content\"\xd6\x01\n" +
	"\x17ListChatMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bmsg_type\x18\x02 \x01(\tR\amsgType\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x10\n" +
	"\x03ids\x18\x04 \x03(\tR\x03ids\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x05 \x03(\tR\tparentIds\x12\x1b\n" +
	"\tpage_size\x18\x15 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x16 \x01(\tR\tpageToken\"t\n" +
	"\x18ListChatMessagesResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.message.ChatMessageR\bmessages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"L\n" +
	"\x18CreateChatMessageRequest\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.message.ChatMessageR\bmessages\"M\n" +
	"\x19CreateChatMessageResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.message.ChatMessageR\bmessages\"L\n" +
	"\x18UpdateChatMessageRequest\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.message.ChatMessageR\bmessages\"M\n" +
	"\x19UpdateChatMessageResponse\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.message.ChatMessageR\bmessages\",\n" +
	"\x18DeleteChatMessageRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"@\n" +
	"\x19DeleteChatMessageResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"\x84\x01\n" +
	"\x19SendConsultMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\ttarget_id\x18\x04 \x01(\tH\x00R\btargetId\x88\x01\x01B\f\n" +
	"\n" +
	"_target_id\"x\n" +
	"\x1aSendConsultMessageResponse\x12.\n" +
	"\aconsult\x18\x01 \x01(\v2\x14.message.ChatMessageR\aconsult\x12*\n" +
	"\x05reply\x18\x02 \x01(\v2\x14.message.ChatMessageR\x05reply\"W\n" +
	"\x19ParseImageMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\"\x82\x01\n" +
	"\x1aParseImageMessagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\bmessages\x18\x03 \x03(\v2\x14.message.ChatMessageR\bmessages\"\xa4\x01\n" +
	"\x18FeedbackToMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1a\n" +
	"\battitude\x18\x03 \x01(\tR\battitude\x12\x1a\n" +
	"\bfeedback\x18\x04 \x01(\tR\bfeedback\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"5\n" +
	"\x19FeedbackToMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x03\n" +
	"\x0eConsultMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x05 \x01(\tR\tprofileId\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x19\n" +
	"\bmsg_type\x18\a \x01(\tR\amsgType\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x121\n" +
	"\x06msg_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x05msgAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:\x02\x18\x01\"\xc9\x01\n" +
	"\x1aListConsultMessagesRequest\x12\x19\n" +
	"\bmsg_type\x18\x01 \x01(\tR\amsgType\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12\x1f\n" +
	"\vsession_ids\x18\x03 \x03(\tR\n" +
	"sessionIds\x12\x1d\n" +
	"\n" +
	"parent_ids\x18\x04 \x03(\tR\tparentIds\x12\x1b\n" +
	"\tpage_size\x18\x15 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x16 \x01(\tR\tpageToken:\x02\x18\x01\"~\n" +
	"\x1bListConsultMessagesResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken:\x02\x18\x01\"V\n" +
	"\x1bUpdateConsultMessageRequest\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages:\x02\x18\x01\"W\n" +
	"\x1cUpdateConsultMessageResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages:\x02\x18\x01\"3\n" +
	"\x1bRecallConsultMessageRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids:\x02\x18\x01\"\"\n" +
	"\x1cRecallConsultMessageResponse:\x02\x18\x01\"z\n" +
	"\x19ListFriendMessagesRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1b\n" +
	"\tpage_size\x18\x15 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x16 \x01(\tR\tpageToken:\x02\x18\x01\"}\n" +
	"\x1aListFriendMessagesResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken:\x02\x18\x01\"U\n" +
	"\x1aCreateFriendMessageRequest\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages:\x02\x18\x01\"V\n" +
	"\x1bCreateFriendMessageResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages:\x02\x18\x01\"U\n" +
	"\x1aUpdateFriendMessageRequest\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages:\x02\x18\x01\"V\n" +
	"\x1bUpdateFriendMessageResponse\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.message.ConsultMessageR\bmessages:\x02\x18\x01\"2\n" +
	"\x1aDeleteFriendMessageRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids:\x02\x18\x01\"!\n" +
	"\x1bDeleteFriendMessageResponse:\x02\x18\x012\xb9\b\n" +
	"\x12ChatMessageService\x12\x90\x01\n" +
	"\x10ListChatMessages\x12 .message.ListChatMessagesRequest\x1a!.message.ListChatMessagesResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/message.ChatMessageService/ListChatMessages\x12\x94\x01\n" +
	"\x11CreateChatMessage\x12!.message.CreateChatMessageRequest\x1a\".message.CreateChatMessageResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/message.ChatMessageService/CreateChatMessage\x12\x94\x01\n" +
	"\x11UpdateChatMessage\x12!.message.UpdateChatMessageRequest\x1a\".message.UpdateChatMessageResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/message.ChatMessageService/UpdateChatMessage\x12\x94\x01\n" +
	"\x11DeleteChatMessage\x12!.message.DeleteChatMessageRequest\x1a\".message.DeleteChatMessageResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/message.ChatMessageService/DeleteChatMessage\x12\x98\x01\n" +
	"\x12SendConsultMessage\x12\".message.SendConsultMessageRequest\x1a#.message.SendConsultMessageResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./message.ChatMessageService/SendConsultMessage\x12\x98\x01\n" +
	"\x12ParseImageMessages\x12\".message.ParseImageMessagesRequest\x1a#.message.ParseImageMessagesResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./message.ChatMessageService/ParseImageMessages\x12\x94\x01\n" +
	"\x11FeedbackToMessage\x12!.message.FeedbackToMessageRequest\x1a\".message.FeedbackToMessageResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/message.ChatMessageService/FeedbackToMessage2\xc8\x02\n" +
	"\x15ConsultMessageService\x12b\n" +
	"\x13ListConsultMessages\x12#.message.ListConsultMessagesRequest\x1a$.message.ListConsultMessagesResponse\"\x00\x12_\n" +
	"\x12SendConsultMessage\x12\".message.SendConsultMessageRequest\x1a#.message.SendConsultMessageResponse\"\x00\x12e\n" +
	"\x14RecallConsultMessage\x12$.message.RecallConsultMessageRequest\x1a%.message.RecallConsultMessageResponse\"\x00\x1a\x03\x88\x02\x012\x89\x04\n" +
	"\x14FriendMessageService\x12_\n" +
	"\x12ListFriendMessages\x12\".message.ListFriendMessagesRequest\x1a#.message.ListFriendMessagesResponse\"\x00\x12b\n" +
	"\x13CreateFriendMessage\x12#.message.CreateFriendMessageRequest\x1a$.message.CreateFriendMessageResponse\"\x00\x12b\n" +
	"\x13UpdateFriendMessage\x12#.message.UpdateFriendMessageRequest\x1a$.message.UpdateFriendMessageResponse\"\x00\x12b\n" +
	"\x13DeleteFriendMessage\x12#.message.DeleteFriendMessageRequest\x1a$.message.DeleteFriendMessageResponse\"\x00\x12_\n" +
	"\x12ParseImageMessages\x12\".message.ParseImageMessagesRequest\x1a#.message.ParseImageMessagesResponse\"\x00\x1a\x03\x88\x02\x01B\x1aZ\x18app_server/proto/messageb\x06proto3"

var (
	file_proto_message_message_proto_rawDescOnce sync.Once
	file_proto_message_message_proto_rawDescData []byte
)

func file_proto_message_message_proto_rawDescGZIP() []byte {
	file_proto_message_message_proto_rawDescOnce.Do(func() {
		file_proto_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_message_proto_rawDesc), len(file_proto_message_message_proto_rawDesc)))
	})
	return file_proto_message_message_proto_rawDescData
}

var file_proto_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_message_message_proto_goTypes = []any{
	(*ChatMessage)(nil),                  // 0: message.ChatMessage
	(*ListChatMessagesRequest)(nil),      // 1: message.ListChatMessagesRequest
	(*ListChatMessagesResponse)(nil),     // 2: message.ListChatMessagesResponse
	(*CreateChatMessageRequest)(nil),     // 3: message.CreateChatMessageRequest
	(*CreateChatMessageResponse)(nil),    // 4: message.CreateChatMessageResponse
	(*UpdateChatMessageRequest)(nil),     // 5: message.UpdateChatMessageRequest
	(*UpdateChatMessageResponse)(nil),    // 6: message.UpdateChatMessageResponse
	(*DeleteChatMessageRequest)(nil),     // 7: message.DeleteChatMessageRequest
	(*DeleteChatMessageResponse)(nil),    // 8: message.DeleteChatMessageResponse
	(*SendConsultMessageRequest)(nil),    // 9: message.SendConsultMessageRequest
	(*SendConsultMessageResponse)(nil),   // 10: message.SendConsultMessageResponse
	(*ParseImageMessagesRequest)(nil),    // 11: message.ParseImageMessagesRequest
	(*ParseImageMessagesResponse)(nil),   // 12: message.ParseImageMessagesResponse
	(*FeedbackToMessageRequest)(nil),     // 13: message.FeedbackToMessageRequest
	(*FeedbackToMessageResponse)(nil),    // 14: message.FeedbackToMessageResponse
	(*ConsultMessage)(nil),               // 15: message.ConsultMessage
	(*ListConsultMessagesRequest)(nil),   // 16: message.ListConsultMessagesRequest
	(*ListConsultMessagesResponse)(nil),  // 17: message.ListConsultMessagesResponse
	(*UpdateConsultMessageRequest)(nil),  // 18: message.UpdateConsultMessageRequest
	(*UpdateConsultMessageResponse)(nil), // 19: message.UpdateConsultMessageResponse
	(*RecallConsultMessageRequest)(nil),  // 20: message.RecallConsultMessageRequest
	(*RecallConsultMessageResponse)(nil), // 21: message.RecallConsultMessageResponse
	(*ListFriendMessagesRequest)(nil),    // 22: message.ListFriendMessagesRequest
	(*ListFriendMessagesResponse)(nil),   // 23: message.ListFriendMessagesResponse
	(*CreateFriendMessageRequest)(nil),   // 24: message.CreateFriendMessageRequest
	(*CreateFriendMessageResponse)(nil),  // 25: message.CreateFriendMessageResponse
	(*UpdateFriendMessageRequest)(nil),   // 26: message.UpdateFriendMessageRequest
	(*UpdateFriendMessageResponse)(nil),  // 27: message.UpdateFriendMessageResponse
	(*DeleteFriendMessageRequest)(nil),   // 28: message.DeleteFriendMessageRequest
	(*DeleteFriendMessageResponse)(nil),  // 29: message.DeleteFriendMessageResponse
	(*timestamppb.Timestamp)(nil),        // 30: google.protobuf.Timestamp
}
var file_proto_message_message_proto_depIdxs = []int32{
	30, // 0: message.ChatMessage.msg_at:type_name -> google.protobuf.Timestamp
	30, // 1: message.ChatMessage.created_at:type_name -> google.protobuf.Timestamp
	30, // 2: message.ChatMessage.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: message.ListChatMessagesResponse.messages:type_name -> message.ChatMessage
	0,  // 4: message.CreateChatMessageRequest.messages:type_name -> message.ChatMessage
	0,  // 5: message.CreateChatMessageResponse.messages:type_name -> message.ChatMessage
	0,  // 6: message.UpdateChatMessageRequest.messages:type_name -> message.ChatMessage
	0,  // 7: message.UpdateChatMessageResponse.messages:type_name -> message.ChatMessage
	0,  // 8: message.SendConsultMessageResponse.consult:type_name -> message.ChatMessage
	0,  // 9: message.SendConsultMessageResponse.reply:type_name -> message.ChatMessage
	0,  // 10: message.ParseImageMessagesResponse.messages:type_name -> message.ChatMessage
	30, // 11: message.ConsultMessage.msg_at:type_name -> google.protobuf.Timestamp
	30, // 12: message.ConsultMessage.created_at:type_name -> google.protobuf.Timestamp
	30, // 13: message.ConsultMessage.updated_at:type_name -> google.protobuf.Timestamp
	15, // 14: message.ListConsultMessagesResponse.messages:type_name -> message.ConsultMessage
	15, // 15: message.UpdateConsultMessageRequest.messages:type_name -> message.ConsultMessage
	15, // 16: message.UpdateConsultMessageResponse.messages:type_name -> message.ConsultMessage
	15, // 17: message.ListFriendMessagesResponse.messages:type_name -> message.ConsultMessage
	15, // 18: message.CreateFriendMessageRequest.messages:type_name -> message.ConsultMessage
	15, // 19: message.CreateFriendMessageResponse.messages:type_name -> message.ConsultMessage
	15, // 20: message.UpdateFriendMessageRequest.messages:type_name -> message.ConsultMessage
	15, // 21: message.UpdateFriendMessageResponse.messages:type_name -> message.ConsultMessage
	1,  // 22: message.ChatMessageService.ListChatMessages:input_type -> message.ListChatMessagesRequest
	3,  // 23: message.ChatMessageService.CreateChatMessage:input_type -> message.CreateChatMessageRequest
	5,  // 24: message.ChatMessageService.UpdateChatMessage:input_type -> message.UpdateChatMessageRequest
	7,  // 25: message.ChatMessageService.DeleteChatMessage:input_type -> message.DeleteChatMessageRequest
	9,  // 26: message.ChatMessageService.SendConsultMessage:input_type -> message.SendConsultMessageRequest
	11, // 27: message.ChatMessageService.ParseImageMessages:input_type -> message.ParseImageMessagesRequest
	13, // 28: message.ChatMessageService.FeedbackToMessage:input_type -> message.FeedbackToMessageRequest
	16, // 29: message.ConsultMessageService.ListConsultMessages:input_type -> message.ListConsultMessagesRequest
	9,  // 30: message.ConsultMessageService.SendConsultMessage:input_type -> message.SendConsultMessageRequest
	20, // 31: message.ConsultMessageService.RecallConsultMessage:input_type -> message.RecallConsultMessageRequest
	22, // 32: message.FriendMessageService.ListFriendMessages:input_type -> message.ListFriendMessagesRequest
	24, // 33: message.FriendMessageService.CreateFriendMessage:input_type -> message.CreateFriendMessageRequest
	26, // 34: message.FriendMessageService.UpdateFriendMessage:input_type -> message.UpdateFriendMessageRequest
	28, // 35: message.FriendMessageService.DeleteFriendMessage:input_type -> message.DeleteFriendMessageRequest
	11, // 36: message.FriendMessageService.ParseImageMessages:input_type -> message.ParseImageMessagesRequest
	2,  // 37: message.ChatMessageService.ListChatMessages:output_type -> message.ListChatMessagesResponse
	4,  // 38: message.ChatMessageService.CreateChatMessage:output_type -> message.CreateChatMessageResponse
	6,  // 39: message.ChatMessageService.UpdateChatMessage:output_type -> message.UpdateChatMessageResponse
	8,  // 40: message.ChatMessageService.DeleteChatMessage:output_type -> message.DeleteChatMessageResponse
	10, // 41: message.ChatMessageService.SendConsultMessage:output_type -> message.SendConsultMessageResponse
	12, // 42: message.ChatMessageService.ParseImageMessages:output_type -> message.ParseImageMessagesResponse
	14, // 43: message.ChatMessageService.FeedbackToMessage:output_type -> message.FeedbackToMessageResponse
	17, // 44: message.ConsultMessageService.ListConsultMessages:output_type -> message.ListConsultMessagesResponse
	10, // 45: message.ConsultMessageService.SendConsultMessage:output_type -> message.SendConsultMessageResponse
	21, // 46: message.ConsultMessageService.RecallConsultMessage:output_type -> message.RecallConsultMessageResponse
	23, // 47: message.FriendMessageService.ListFriendMessages:output_type -> message.ListFriendMessagesResponse
	25, // 48: message.FriendMessageService.CreateFriendMessage:output_type -> message.CreateFriendMessageResponse
	27, // 49: message.FriendMessageService.UpdateFriendMessage:output_type -> message.UpdateFriendMessageResponse
	29, // 50: message.FriendMessageService.DeleteFriendMessage:output_type -> message.DeleteFriendMessageResponse
	12, // 51: message.FriendMessageService.ParseImageMessages:output_type -> message.ParseImageMessagesResponse
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_message_message_proto_init() }
func file_proto_message_message_proto_init() {
	if File_proto_message_message_proto != nil {
		return
	}
	file_proto_message_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_message_message_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_message_proto_rawDesc), len(file_proto_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_message_message_proto_goTypes,
		DependencyIndexes: file_proto_message_message_proto_depIdxs,
		MessageInfos:      file_proto_message_message_proto_msgTypes,
	}.Build()
	File_proto_message_message_proto = out.File
	file_proto_message_message_proto_goTypes = nil
	file_proto_message_message_proto_depIdxs = nil
}
