// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/chat/chat.proto

package chatconnect

import (
	chat "app_server/proto/chat"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChatServiceName is the fully-qualified name of the ChatService service.
	ChatServiceName = "chat.ChatService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatServiceListChatSessionsProcedure is the fully-qualified name of the ChatService's
	// ListChatSessions RPC.
	ChatServiceListChatSessionsProcedure = "/chat.ChatService/ListChatSessions"
	// ChatServiceCreateChatSessionProcedure is the fully-qualified name of the ChatService's
	// CreateChatSession RPC.
	ChatServiceCreateChatSessionProcedure = "/chat.ChatService/CreateChatSession"
	// ChatServiceDeleteChatSessionProcedure is the fully-qualified name of the ChatService's
	// DeleteChatSession RPC.
	ChatServiceDeleteChatSessionProcedure = "/chat.ChatService/DeleteChatSession"
	// ChatServiceUpdateChatSessionProcedure is the fully-qualified name of the ChatService's
	// UpdateChatSession RPC.
	ChatServiceUpdateChatSessionProcedure = "/chat.ChatService/UpdateChatSession"
)

// ChatServiceClient is a client for the chat.ChatService service.
type ChatServiceClient interface {
	// POST /chat.ChatService/ListChatSessions
	ListChatSessions(context.Context, *connect.Request[chat.ListChatSessionsRequest]) (*connect.Response[chat.ListChatSessionsResponse], error)
	// POST /chat.ChatService/CreateChatSession
	CreateChatSession(context.Context, *connect.Request[chat.CreateChatSessionRequest]) (*connect.Response[chat.CreateChatSessionResponse], error)
	// POST /chat.ChatService/DeleteChatSession
	DeleteChatSession(context.Context, *connect.Request[chat.DeleteChatSessionRequest]) (*connect.Response[chat.DeleteChatSessionResponse], error)
	// POST /chat.ChatService/UpdateChatSession
	UpdateChatSession(context.Context, *connect.Request[chat.UpdateChatSessionRequest]) (*connect.Response[chat.UpdateChatSessionResponse], error)
}

// NewChatServiceClient constructs a client for the chat.ChatService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChatServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chatServiceMethods := chat.File_proto_chat_chat_proto.Services().ByName("ChatService").Methods()
	return &chatServiceClient{
		listChatSessions: connect.NewClient[chat.ListChatSessionsRequest, chat.ListChatSessionsResponse](
			httpClient,
			baseURL+ChatServiceListChatSessionsProcedure,
			connect.WithSchema(chatServiceMethods.ByName("ListChatSessions")),
			connect.WithClientOptions(opts...),
		),
		createChatSession: connect.NewClient[chat.CreateChatSessionRequest, chat.CreateChatSessionResponse](
			httpClient,
			baseURL+ChatServiceCreateChatSessionProcedure,
			connect.WithSchema(chatServiceMethods.ByName("CreateChatSession")),
			connect.WithClientOptions(opts...),
		),
		deleteChatSession: connect.NewClient[chat.DeleteChatSessionRequest, chat.DeleteChatSessionResponse](
			httpClient,
			baseURL+ChatServiceDeleteChatSessionProcedure,
			connect.WithSchema(chatServiceMethods.ByName("DeleteChatSession")),
			connect.WithClientOptions(opts...),
		),
		updateChatSession: connect.NewClient[chat.UpdateChatSessionRequest, chat.UpdateChatSessionResponse](
			httpClient,
			baseURL+ChatServiceUpdateChatSessionProcedure,
			connect.WithSchema(chatServiceMethods.ByName("UpdateChatSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chatServiceClient implements ChatServiceClient.
type chatServiceClient struct {
	listChatSessions  *connect.Client[chat.ListChatSessionsRequest, chat.ListChatSessionsResponse]
	createChatSession *connect.Client[chat.CreateChatSessionRequest, chat.CreateChatSessionResponse]
	deleteChatSession *connect.Client[chat.DeleteChatSessionRequest, chat.DeleteChatSessionResponse]
	updateChatSession *connect.Client[chat.UpdateChatSessionRequest, chat.UpdateChatSessionResponse]
}

// ListChatSessions calls chat.ChatService.ListChatSessions.
func (c *chatServiceClient) ListChatSessions(ctx context.Context, req *connect.Request[chat.ListChatSessionsRequest]) (*connect.Response[chat.ListChatSessionsResponse], error) {
	return c.listChatSessions.CallUnary(ctx, req)
}

// CreateChatSession calls chat.ChatService.CreateChatSession.
func (c *chatServiceClient) CreateChatSession(ctx context.Context, req *connect.Request[chat.CreateChatSessionRequest]) (*connect.Response[chat.CreateChatSessionResponse], error) {
	return c.createChatSession.CallUnary(ctx, req)
}

// DeleteChatSession calls chat.ChatService.DeleteChatSession.
func (c *chatServiceClient) DeleteChatSession(ctx context.Context, req *connect.Request[chat.DeleteChatSessionRequest]) (*connect.Response[chat.DeleteChatSessionResponse], error) {
	return c.deleteChatSession.CallUnary(ctx, req)
}

// UpdateChatSession calls chat.ChatService.UpdateChatSession.
func (c *chatServiceClient) UpdateChatSession(ctx context.Context, req *connect.Request[chat.UpdateChatSessionRequest]) (*connect.Response[chat.UpdateChatSessionResponse], error) {
	return c.updateChatSession.CallUnary(ctx, req)
}

// ChatServiceHandler is an implementation of the chat.ChatService service.
type ChatServiceHandler interface {
	// POST /chat.ChatService/ListChatSessions
	ListChatSessions(context.Context, *connect.Request[chat.ListChatSessionsRequest]) (*connect.Response[chat.ListChatSessionsResponse], error)
	// POST /chat.ChatService/CreateChatSession
	CreateChatSession(context.Context, *connect.Request[chat.CreateChatSessionRequest]) (*connect.Response[chat.CreateChatSessionResponse], error)
	// POST /chat.ChatService/DeleteChatSession
	DeleteChatSession(context.Context, *connect.Request[chat.DeleteChatSessionRequest]) (*connect.Response[chat.DeleteChatSessionResponse], error)
	// POST /chat.ChatService/UpdateChatSession
	UpdateChatSession(context.Context, *connect.Request[chat.UpdateChatSessionRequest]) (*connect.Response[chat.UpdateChatSessionResponse], error)
}

// NewChatServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatServiceHandler(svc ChatServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chatServiceMethods := chat.File_proto_chat_chat_proto.Services().ByName("ChatService").Methods()
	chatServiceListChatSessionsHandler := connect.NewUnaryHandler(
		ChatServiceListChatSessionsProcedure,
		svc.ListChatSessions,
		connect.WithSchema(chatServiceMethods.ByName("ListChatSessions")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceCreateChatSessionHandler := connect.NewUnaryHandler(
		ChatServiceCreateChatSessionProcedure,
		svc.CreateChatSession,
		connect.WithSchema(chatServiceMethods.ByName("CreateChatSession")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceDeleteChatSessionHandler := connect.NewUnaryHandler(
		ChatServiceDeleteChatSessionProcedure,
		svc.DeleteChatSession,
		connect.WithSchema(chatServiceMethods.ByName("DeleteChatSession")),
		connect.WithHandlerOptions(opts...),
	)
	chatServiceUpdateChatSessionHandler := connect.NewUnaryHandler(
		ChatServiceUpdateChatSessionProcedure,
		svc.UpdateChatSession,
		connect.WithSchema(chatServiceMethods.ByName("UpdateChatSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chat.ChatService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatServiceListChatSessionsProcedure:
			chatServiceListChatSessionsHandler.ServeHTTP(w, r)
		case ChatServiceCreateChatSessionProcedure:
			chatServiceCreateChatSessionHandler.ServeHTTP(w, r)
		case ChatServiceDeleteChatSessionProcedure:
			chatServiceDeleteChatSessionHandler.ServeHTTP(w, r)
		case ChatServiceUpdateChatSessionProcedure:
			chatServiceUpdateChatSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatServiceHandler struct{}

func (UnimplementedChatServiceHandler) ListChatSessions(context.Context, *connect.Request[chat.ListChatSessionsRequest]) (*connect.Response[chat.ListChatSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.ChatService.ListChatSessions is not implemented"))
}

func (UnimplementedChatServiceHandler) CreateChatSession(context.Context, *connect.Request[chat.CreateChatSessionRequest]) (*connect.Response[chat.CreateChatSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.ChatService.CreateChatSession is not implemented"))
}

func (UnimplementedChatServiceHandler) DeleteChatSession(context.Context, *connect.Request[chat.DeleteChatSessionRequest]) (*connect.Response[chat.DeleteChatSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.ChatService.DeleteChatSession is not implemented"))
}

func (UnimplementedChatServiceHandler) UpdateChatSession(context.Context, *connect.Request[chat.UpdateChatSessionRequest]) (*connect.Response[chat.UpdateChatSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chat.ChatService.UpdateChatSession is not implemented"))
}
