// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/message/message.proto

package messageconnect

import (
	message "app_server/proto/message"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChatMessageServiceName is the fully-qualified name of the ChatMessageService service.
	ChatMessageServiceName = "message.ChatMessageService"
	// ConsultMessageServiceName is the fully-qualified name of the ConsultMessageService service.
	ConsultMessageServiceName = "message.ConsultMessageService"
	// FriendMessageServiceName is the fully-qualified name of the FriendMessageService service.
	FriendMessageServiceName = "message.FriendMessageService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChatMessageServiceListChatMessagesProcedure is the fully-qualified name of the
	// ChatMessageService's ListChatMessages RPC.
	ChatMessageServiceListChatMessagesProcedure = "/message.ChatMessageService/ListChatMessages"
	// ChatMessageServiceCreateChatMessageProcedure is the fully-qualified name of the
	// ChatMessageService's CreateChatMessage RPC.
	ChatMessageServiceCreateChatMessageProcedure = "/message.ChatMessageService/CreateChatMessage"
	// ChatMessageServiceUpdateChatMessageProcedure is the fully-qualified name of the
	// ChatMessageService's UpdateChatMessage RPC.
	ChatMessageServiceUpdateChatMessageProcedure = "/message.ChatMessageService/UpdateChatMessage"
	// ChatMessageServiceDeleteChatMessageProcedure is the fully-qualified name of the
	// ChatMessageService's DeleteChatMessage RPC.
	ChatMessageServiceDeleteChatMessageProcedure = "/message.ChatMessageService/DeleteChatMessage"
	// ChatMessageServiceSendConsultMessageProcedure is the fully-qualified name of the
	// ChatMessageService's SendConsultMessage RPC.
	ChatMessageServiceSendConsultMessageProcedure = "/message.ChatMessageService/SendConsultMessage"
	// ChatMessageServiceParseImageMessagesProcedure is the fully-qualified name of the
	// ChatMessageService's ParseImageMessages RPC.
	ChatMessageServiceParseImageMessagesProcedure = "/message.ChatMessageService/ParseImageMessages"
	// ChatMessageServiceFeedbackToMessageProcedure is the fully-qualified name of the
	// ChatMessageService's FeedbackToMessage RPC.
	ChatMessageServiceFeedbackToMessageProcedure = "/message.ChatMessageService/FeedbackToMessage"
	// ConsultMessageServiceListConsultMessagesProcedure is the fully-qualified name of the
	// ConsultMessageService's ListConsultMessages RPC.
	ConsultMessageServiceListConsultMessagesProcedure = "/message.ConsultMessageService/ListConsultMessages"
	// ConsultMessageServiceSendConsultMessageProcedure is the fully-qualified name of the
	// ConsultMessageService's SendConsultMessage RPC.
	ConsultMessageServiceSendConsultMessageProcedure = "/message.ConsultMessageService/SendConsultMessage"
	// ConsultMessageServiceRecallConsultMessageProcedure is the fully-qualified name of the
	// ConsultMessageService's RecallConsultMessage RPC.
	ConsultMessageServiceRecallConsultMessageProcedure = "/message.ConsultMessageService/RecallConsultMessage"
	// FriendMessageServiceListFriendMessagesProcedure is the fully-qualified name of the
	// FriendMessageService's ListFriendMessages RPC.
	FriendMessageServiceListFriendMessagesProcedure = "/message.FriendMessageService/ListFriendMessages"
	// FriendMessageServiceCreateFriendMessageProcedure is the fully-qualified name of the
	// FriendMessageService's CreateFriendMessage RPC.
	FriendMessageServiceCreateFriendMessageProcedure = "/message.FriendMessageService/CreateFriendMessage"
	// FriendMessageServiceUpdateFriendMessageProcedure is the fully-qualified name of the
	// FriendMessageService's UpdateFriendMessage RPC.
	FriendMessageServiceUpdateFriendMessageProcedure = "/message.FriendMessageService/UpdateFriendMessage"
	// FriendMessageServiceDeleteFriendMessageProcedure is the fully-qualified name of the
	// FriendMessageService's DeleteFriendMessage RPC.
	FriendMessageServiceDeleteFriendMessageProcedure = "/message.FriendMessageService/DeleteFriendMessage"
	// FriendMessageServiceParseImageMessagesProcedure is the fully-qualified name of the
	// FriendMessageService's ParseImageMessages RPC.
	FriendMessageServiceParseImageMessagesProcedure = "/message.FriendMessageService/ParseImageMessages"
)

// ChatMessageServiceClient is a client for the message.ChatMessageService service.
type ChatMessageServiceClient interface {
	// 查询消息列表 - 合并原来的 ListConsultMessages 和 ListFriendMessages
	// POST /message.ChatMessageService/ListChatMessages
	ListChatMessages(context.Context, *connect.Request[message.ListChatMessagesRequest]) (*connect.Response[message.ListChatMessagesResponse], error)
	// 创建消息 - 合并原来的 SendConsultMessage 和 CreateFriendMessage
	// POST /message.ChatMessageService/CreateChatMessage
	CreateChatMessage(context.Context, *connect.Request[message.CreateChatMessageRequest]) (*connect.Response[message.CreateChatMessageResponse], error)
	// 更新消息
	// POST /message.ChatMessageService/UpdateChatMessage
	UpdateChatMessage(context.Context, *connect.Request[message.UpdateChatMessageRequest]) (*connect.Response[message.UpdateChatMessageResponse], error)
	// 删除消息 - 合并原来的 RecallConsultMessage 和 DeleteFriendMessage
	// POST /message.ChatMessageService/DeleteChatMessage
	DeleteChatMessage(context.Context, *connect.Request[message.DeleteChatMessageRequest]) (*connect.Response[message.DeleteChatMessageResponse], error)
	// 发送咨询消息 - 专门用于AI咨询回复
	// POST /message.ChatMessageService/SendConsultMessage
	SendConsultMessage(context.Context, *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error)
	// 解析图片中的消息（保留原功能）
	// POST /message.ChatMessageService/ParseImageMessages
	ParseImageMessages(context.Context, *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error)
	// 用户反馈 点赞/踩/评论
	// POST /message.ChatMessageService/FeedbackToMessage
	FeedbackToMessage(context.Context, *connect.Request[message.FeedbackToMessageRequest]) (*connect.Response[message.FeedbackToMessageResponse], error)
}

// NewChatMessageServiceClient constructs a client for the message.ChatMessageService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChatMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChatMessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	chatMessageServiceMethods := message.File_proto_message_message_proto.Services().ByName("ChatMessageService").Methods()
	return &chatMessageServiceClient{
		listChatMessages: connect.NewClient[message.ListChatMessagesRequest, message.ListChatMessagesResponse](
			httpClient,
			baseURL+ChatMessageServiceListChatMessagesProcedure,
			connect.WithSchema(chatMessageServiceMethods.ByName("ListChatMessages")),
			connect.WithClientOptions(opts...),
		),
		createChatMessage: connect.NewClient[message.CreateChatMessageRequest, message.CreateChatMessageResponse](
			httpClient,
			baseURL+ChatMessageServiceCreateChatMessageProcedure,
			connect.WithSchema(chatMessageServiceMethods.ByName("CreateChatMessage")),
			connect.WithClientOptions(opts...),
		),
		updateChatMessage: connect.NewClient[message.UpdateChatMessageRequest, message.UpdateChatMessageResponse](
			httpClient,
			baseURL+ChatMessageServiceUpdateChatMessageProcedure,
			connect.WithSchema(chatMessageServiceMethods.ByName("UpdateChatMessage")),
			connect.WithClientOptions(opts...),
		),
		deleteChatMessage: connect.NewClient[message.DeleteChatMessageRequest, message.DeleteChatMessageResponse](
			httpClient,
			baseURL+ChatMessageServiceDeleteChatMessageProcedure,
			connect.WithSchema(chatMessageServiceMethods.ByName("DeleteChatMessage")),
			connect.WithClientOptions(opts...),
		),
		sendConsultMessage: connect.NewClient[message.SendConsultMessageRequest, message.SendConsultMessageResponse](
			httpClient,
			baseURL+ChatMessageServiceSendConsultMessageProcedure,
			connect.WithSchema(chatMessageServiceMethods.ByName("SendConsultMessage")),
			connect.WithClientOptions(opts...),
		),
		parseImageMessages: connect.NewClient[message.ParseImageMessagesRequest, message.ParseImageMessagesResponse](
			httpClient,
			baseURL+ChatMessageServiceParseImageMessagesProcedure,
			connect.WithSchema(chatMessageServiceMethods.ByName("ParseImageMessages")),
			connect.WithClientOptions(opts...),
		),
		feedbackToMessage: connect.NewClient[message.FeedbackToMessageRequest, message.FeedbackToMessageResponse](
			httpClient,
			baseURL+ChatMessageServiceFeedbackToMessageProcedure,
			connect.WithSchema(chatMessageServiceMethods.ByName("FeedbackToMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// chatMessageServiceClient implements ChatMessageServiceClient.
type chatMessageServiceClient struct {
	listChatMessages   *connect.Client[message.ListChatMessagesRequest, message.ListChatMessagesResponse]
	createChatMessage  *connect.Client[message.CreateChatMessageRequest, message.CreateChatMessageResponse]
	updateChatMessage  *connect.Client[message.UpdateChatMessageRequest, message.UpdateChatMessageResponse]
	deleteChatMessage  *connect.Client[message.DeleteChatMessageRequest, message.DeleteChatMessageResponse]
	sendConsultMessage *connect.Client[message.SendConsultMessageRequest, message.SendConsultMessageResponse]
	parseImageMessages *connect.Client[message.ParseImageMessagesRequest, message.ParseImageMessagesResponse]
	feedbackToMessage  *connect.Client[message.FeedbackToMessageRequest, message.FeedbackToMessageResponse]
}

// ListChatMessages calls message.ChatMessageService.ListChatMessages.
func (c *chatMessageServiceClient) ListChatMessages(ctx context.Context, req *connect.Request[message.ListChatMessagesRequest]) (*connect.Response[message.ListChatMessagesResponse], error) {
	return c.listChatMessages.CallUnary(ctx, req)
}

// CreateChatMessage calls message.ChatMessageService.CreateChatMessage.
func (c *chatMessageServiceClient) CreateChatMessage(ctx context.Context, req *connect.Request[message.CreateChatMessageRequest]) (*connect.Response[message.CreateChatMessageResponse], error) {
	return c.createChatMessage.CallUnary(ctx, req)
}

// UpdateChatMessage calls message.ChatMessageService.UpdateChatMessage.
func (c *chatMessageServiceClient) UpdateChatMessage(ctx context.Context, req *connect.Request[message.UpdateChatMessageRequest]) (*connect.Response[message.UpdateChatMessageResponse], error) {
	return c.updateChatMessage.CallUnary(ctx, req)
}

// DeleteChatMessage calls message.ChatMessageService.DeleteChatMessage.
func (c *chatMessageServiceClient) DeleteChatMessage(ctx context.Context, req *connect.Request[message.DeleteChatMessageRequest]) (*connect.Response[message.DeleteChatMessageResponse], error) {
	return c.deleteChatMessage.CallUnary(ctx, req)
}

// SendConsultMessage calls message.ChatMessageService.SendConsultMessage.
func (c *chatMessageServiceClient) SendConsultMessage(ctx context.Context, req *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error) {
	return c.sendConsultMessage.CallUnary(ctx, req)
}

// ParseImageMessages calls message.ChatMessageService.ParseImageMessages.
func (c *chatMessageServiceClient) ParseImageMessages(ctx context.Context, req *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error) {
	return c.parseImageMessages.CallUnary(ctx, req)
}

// FeedbackToMessage calls message.ChatMessageService.FeedbackToMessage.
func (c *chatMessageServiceClient) FeedbackToMessage(ctx context.Context, req *connect.Request[message.FeedbackToMessageRequest]) (*connect.Response[message.FeedbackToMessageResponse], error) {
	return c.feedbackToMessage.CallUnary(ctx, req)
}

// ChatMessageServiceHandler is an implementation of the message.ChatMessageService service.
type ChatMessageServiceHandler interface {
	// 查询消息列表 - 合并原来的 ListConsultMessages 和 ListFriendMessages
	// POST /message.ChatMessageService/ListChatMessages
	ListChatMessages(context.Context, *connect.Request[message.ListChatMessagesRequest]) (*connect.Response[message.ListChatMessagesResponse], error)
	// 创建消息 - 合并原来的 SendConsultMessage 和 CreateFriendMessage
	// POST /message.ChatMessageService/CreateChatMessage
	CreateChatMessage(context.Context, *connect.Request[message.CreateChatMessageRequest]) (*connect.Response[message.CreateChatMessageResponse], error)
	// 更新消息
	// POST /message.ChatMessageService/UpdateChatMessage
	UpdateChatMessage(context.Context, *connect.Request[message.UpdateChatMessageRequest]) (*connect.Response[message.UpdateChatMessageResponse], error)
	// 删除消息 - 合并原来的 RecallConsultMessage 和 DeleteFriendMessage
	// POST /message.ChatMessageService/DeleteChatMessage
	DeleteChatMessage(context.Context, *connect.Request[message.DeleteChatMessageRequest]) (*connect.Response[message.DeleteChatMessageResponse], error)
	// 发送咨询消息 - 专门用于AI咨询回复
	// POST /message.ChatMessageService/SendConsultMessage
	SendConsultMessage(context.Context, *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error)
	// 解析图片中的消息（保留原功能）
	// POST /message.ChatMessageService/ParseImageMessages
	ParseImageMessages(context.Context, *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error)
	// 用户反馈 点赞/踩/评论
	// POST /message.ChatMessageService/FeedbackToMessage
	FeedbackToMessage(context.Context, *connect.Request[message.FeedbackToMessageRequest]) (*connect.Response[message.FeedbackToMessageResponse], error)
}

// NewChatMessageServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChatMessageServiceHandler(svc ChatMessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	chatMessageServiceMethods := message.File_proto_message_message_proto.Services().ByName("ChatMessageService").Methods()
	chatMessageServiceListChatMessagesHandler := connect.NewUnaryHandler(
		ChatMessageServiceListChatMessagesProcedure,
		svc.ListChatMessages,
		connect.WithSchema(chatMessageServiceMethods.ByName("ListChatMessages")),
		connect.WithHandlerOptions(opts...),
	)
	chatMessageServiceCreateChatMessageHandler := connect.NewUnaryHandler(
		ChatMessageServiceCreateChatMessageProcedure,
		svc.CreateChatMessage,
		connect.WithSchema(chatMessageServiceMethods.ByName("CreateChatMessage")),
		connect.WithHandlerOptions(opts...),
	)
	chatMessageServiceUpdateChatMessageHandler := connect.NewUnaryHandler(
		ChatMessageServiceUpdateChatMessageProcedure,
		svc.UpdateChatMessage,
		connect.WithSchema(chatMessageServiceMethods.ByName("UpdateChatMessage")),
		connect.WithHandlerOptions(opts...),
	)
	chatMessageServiceDeleteChatMessageHandler := connect.NewUnaryHandler(
		ChatMessageServiceDeleteChatMessageProcedure,
		svc.DeleteChatMessage,
		connect.WithSchema(chatMessageServiceMethods.ByName("DeleteChatMessage")),
		connect.WithHandlerOptions(opts...),
	)
	chatMessageServiceSendConsultMessageHandler := connect.NewUnaryHandler(
		ChatMessageServiceSendConsultMessageProcedure,
		svc.SendConsultMessage,
		connect.WithSchema(chatMessageServiceMethods.ByName("SendConsultMessage")),
		connect.WithHandlerOptions(opts...),
	)
	chatMessageServiceParseImageMessagesHandler := connect.NewUnaryHandler(
		ChatMessageServiceParseImageMessagesProcedure,
		svc.ParseImageMessages,
		connect.WithSchema(chatMessageServiceMethods.ByName("ParseImageMessages")),
		connect.WithHandlerOptions(opts...),
	)
	chatMessageServiceFeedbackToMessageHandler := connect.NewUnaryHandler(
		ChatMessageServiceFeedbackToMessageProcedure,
		svc.FeedbackToMessage,
		connect.WithSchema(chatMessageServiceMethods.ByName("FeedbackToMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/message.ChatMessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChatMessageServiceListChatMessagesProcedure:
			chatMessageServiceListChatMessagesHandler.ServeHTTP(w, r)
		case ChatMessageServiceCreateChatMessageProcedure:
			chatMessageServiceCreateChatMessageHandler.ServeHTTP(w, r)
		case ChatMessageServiceUpdateChatMessageProcedure:
			chatMessageServiceUpdateChatMessageHandler.ServeHTTP(w, r)
		case ChatMessageServiceDeleteChatMessageProcedure:
			chatMessageServiceDeleteChatMessageHandler.ServeHTTP(w, r)
		case ChatMessageServiceSendConsultMessageProcedure:
			chatMessageServiceSendConsultMessageHandler.ServeHTTP(w, r)
		case ChatMessageServiceParseImageMessagesProcedure:
			chatMessageServiceParseImageMessagesHandler.ServeHTTP(w, r)
		case ChatMessageServiceFeedbackToMessageProcedure:
			chatMessageServiceFeedbackToMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChatMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChatMessageServiceHandler struct{}

func (UnimplementedChatMessageServiceHandler) ListChatMessages(context.Context, *connect.Request[message.ListChatMessagesRequest]) (*connect.Response[message.ListChatMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ChatMessageService.ListChatMessages is not implemented"))
}

func (UnimplementedChatMessageServiceHandler) CreateChatMessage(context.Context, *connect.Request[message.CreateChatMessageRequest]) (*connect.Response[message.CreateChatMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ChatMessageService.CreateChatMessage is not implemented"))
}

func (UnimplementedChatMessageServiceHandler) UpdateChatMessage(context.Context, *connect.Request[message.UpdateChatMessageRequest]) (*connect.Response[message.UpdateChatMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ChatMessageService.UpdateChatMessage is not implemented"))
}

func (UnimplementedChatMessageServiceHandler) DeleteChatMessage(context.Context, *connect.Request[message.DeleteChatMessageRequest]) (*connect.Response[message.DeleteChatMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ChatMessageService.DeleteChatMessage is not implemented"))
}

func (UnimplementedChatMessageServiceHandler) SendConsultMessage(context.Context, *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ChatMessageService.SendConsultMessage is not implemented"))
}

func (UnimplementedChatMessageServiceHandler) ParseImageMessages(context.Context, *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ChatMessageService.ParseImageMessages is not implemented"))
}

func (UnimplementedChatMessageServiceHandler) FeedbackToMessage(context.Context, *connect.Request[message.FeedbackToMessageRequest]) (*connect.Response[message.FeedbackToMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ChatMessageService.FeedbackToMessage is not implemented"))
}

// ConsultMessageServiceClient is a client for the message.ConsultMessageService service.
//
// Deprecated: do not use.
type ConsultMessageServiceClient interface {
	ListConsultMessages(context.Context, *connect.Request[message.ListConsultMessagesRequest]) (*connect.Response[message.ListConsultMessagesResponse], error)
	SendConsultMessage(context.Context, *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error)
	RecallConsultMessage(context.Context, *connect.Request[message.RecallConsultMessageRequest]) (*connect.Response[message.RecallConsultMessageResponse], error)
}

// NewConsultMessageServiceClient constructs a client for the message.ConsultMessageService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
//
// Deprecated: do not use.
func NewConsultMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConsultMessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	consultMessageServiceMethods := message.File_proto_message_message_proto.Services().ByName("ConsultMessageService").Methods()
	return &consultMessageServiceClient{
		listConsultMessages: connect.NewClient[message.ListConsultMessagesRequest, message.ListConsultMessagesResponse](
			httpClient,
			baseURL+ConsultMessageServiceListConsultMessagesProcedure,
			connect.WithSchema(consultMessageServiceMethods.ByName("ListConsultMessages")),
			connect.WithClientOptions(opts...),
		),
		sendConsultMessage: connect.NewClient[message.SendConsultMessageRequest, message.SendConsultMessageResponse](
			httpClient,
			baseURL+ConsultMessageServiceSendConsultMessageProcedure,
			connect.WithSchema(consultMessageServiceMethods.ByName("SendConsultMessage")),
			connect.WithClientOptions(opts...),
		),
		recallConsultMessage: connect.NewClient[message.RecallConsultMessageRequest, message.RecallConsultMessageResponse](
			httpClient,
			baseURL+ConsultMessageServiceRecallConsultMessageProcedure,
			connect.WithSchema(consultMessageServiceMethods.ByName("RecallConsultMessage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// consultMessageServiceClient implements ConsultMessageServiceClient.
type consultMessageServiceClient struct {
	listConsultMessages  *connect.Client[message.ListConsultMessagesRequest, message.ListConsultMessagesResponse]
	sendConsultMessage   *connect.Client[message.SendConsultMessageRequest, message.SendConsultMessageResponse]
	recallConsultMessage *connect.Client[message.RecallConsultMessageRequest, message.RecallConsultMessageResponse]
}

// ListConsultMessages calls message.ConsultMessageService.ListConsultMessages.
func (c *consultMessageServiceClient) ListConsultMessages(ctx context.Context, req *connect.Request[message.ListConsultMessagesRequest]) (*connect.Response[message.ListConsultMessagesResponse], error) {
	return c.listConsultMessages.CallUnary(ctx, req)
}

// SendConsultMessage calls message.ConsultMessageService.SendConsultMessage.
func (c *consultMessageServiceClient) SendConsultMessage(ctx context.Context, req *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error) {
	return c.sendConsultMessage.CallUnary(ctx, req)
}

// RecallConsultMessage calls message.ConsultMessageService.RecallConsultMessage.
func (c *consultMessageServiceClient) RecallConsultMessage(ctx context.Context, req *connect.Request[message.RecallConsultMessageRequest]) (*connect.Response[message.RecallConsultMessageResponse], error) {
	return c.recallConsultMessage.CallUnary(ctx, req)
}

// ConsultMessageServiceHandler is an implementation of the message.ConsultMessageService service.
//
// Deprecated: do not use.
type ConsultMessageServiceHandler interface {
	ListConsultMessages(context.Context, *connect.Request[message.ListConsultMessagesRequest]) (*connect.Response[message.ListConsultMessagesResponse], error)
	SendConsultMessage(context.Context, *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error)
	RecallConsultMessage(context.Context, *connect.Request[message.RecallConsultMessageRequest]) (*connect.Response[message.RecallConsultMessageResponse], error)
}

// NewConsultMessageServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
//
// Deprecated: do not use.
func NewConsultMessageServiceHandler(svc ConsultMessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	consultMessageServiceMethods := message.File_proto_message_message_proto.Services().ByName("ConsultMessageService").Methods()
	consultMessageServiceListConsultMessagesHandler := connect.NewUnaryHandler(
		ConsultMessageServiceListConsultMessagesProcedure,
		svc.ListConsultMessages,
		connect.WithSchema(consultMessageServiceMethods.ByName("ListConsultMessages")),
		connect.WithHandlerOptions(opts...),
	)
	consultMessageServiceSendConsultMessageHandler := connect.NewUnaryHandler(
		ConsultMessageServiceSendConsultMessageProcedure,
		svc.SendConsultMessage,
		connect.WithSchema(consultMessageServiceMethods.ByName("SendConsultMessage")),
		connect.WithHandlerOptions(opts...),
	)
	consultMessageServiceRecallConsultMessageHandler := connect.NewUnaryHandler(
		ConsultMessageServiceRecallConsultMessageProcedure,
		svc.RecallConsultMessage,
		connect.WithSchema(consultMessageServiceMethods.ByName("RecallConsultMessage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/message.ConsultMessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConsultMessageServiceListConsultMessagesProcedure:
			consultMessageServiceListConsultMessagesHandler.ServeHTTP(w, r)
		case ConsultMessageServiceSendConsultMessageProcedure:
			consultMessageServiceSendConsultMessageHandler.ServeHTTP(w, r)
		case ConsultMessageServiceRecallConsultMessageProcedure:
			consultMessageServiceRecallConsultMessageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConsultMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConsultMessageServiceHandler struct{}

func (UnimplementedConsultMessageServiceHandler) ListConsultMessages(context.Context, *connect.Request[message.ListConsultMessagesRequest]) (*connect.Response[message.ListConsultMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ConsultMessageService.ListConsultMessages is not implemented"))
}

func (UnimplementedConsultMessageServiceHandler) SendConsultMessage(context.Context, *connect.Request[message.SendConsultMessageRequest]) (*connect.Response[message.SendConsultMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ConsultMessageService.SendConsultMessage is not implemented"))
}

func (UnimplementedConsultMessageServiceHandler) RecallConsultMessage(context.Context, *connect.Request[message.RecallConsultMessageRequest]) (*connect.Response[message.RecallConsultMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.ConsultMessageService.RecallConsultMessage is not implemented"))
}

// FriendMessageServiceClient is a client for the message.FriendMessageService service.
//
// Deprecated: do not use.
type FriendMessageServiceClient interface {
	ListFriendMessages(context.Context, *connect.Request[message.ListFriendMessagesRequest]) (*connect.Response[message.ListFriendMessagesResponse], error)
	CreateFriendMessage(context.Context, *connect.Request[message.CreateFriendMessageRequest]) (*connect.Response[message.CreateFriendMessageResponse], error)
	UpdateFriendMessage(context.Context, *connect.Request[message.UpdateFriendMessageRequest]) (*connect.Response[message.UpdateFriendMessageResponse], error)
	DeleteFriendMessage(context.Context, *connect.Request[message.DeleteFriendMessageRequest]) (*connect.Response[message.DeleteFriendMessageResponse], error)
	ParseImageMessages(context.Context, *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error)
}

// NewFriendMessageServiceClient constructs a client for the message.FriendMessageService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
//
// Deprecated: do not use.
func NewFriendMessageServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FriendMessageServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	friendMessageServiceMethods := message.File_proto_message_message_proto.Services().ByName("FriendMessageService").Methods()
	return &friendMessageServiceClient{
		listFriendMessages: connect.NewClient[message.ListFriendMessagesRequest, message.ListFriendMessagesResponse](
			httpClient,
			baseURL+FriendMessageServiceListFriendMessagesProcedure,
			connect.WithSchema(friendMessageServiceMethods.ByName("ListFriendMessages")),
			connect.WithClientOptions(opts...),
		),
		createFriendMessage: connect.NewClient[message.CreateFriendMessageRequest, message.CreateFriendMessageResponse](
			httpClient,
			baseURL+FriendMessageServiceCreateFriendMessageProcedure,
			connect.WithSchema(friendMessageServiceMethods.ByName("CreateFriendMessage")),
			connect.WithClientOptions(opts...),
		),
		updateFriendMessage: connect.NewClient[message.UpdateFriendMessageRequest, message.UpdateFriendMessageResponse](
			httpClient,
			baseURL+FriendMessageServiceUpdateFriendMessageProcedure,
			connect.WithSchema(friendMessageServiceMethods.ByName("UpdateFriendMessage")),
			connect.WithClientOptions(opts...),
		),
		deleteFriendMessage: connect.NewClient[message.DeleteFriendMessageRequest, message.DeleteFriendMessageResponse](
			httpClient,
			baseURL+FriendMessageServiceDeleteFriendMessageProcedure,
			connect.WithSchema(friendMessageServiceMethods.ByName("DeleteFriendMessage")),
			connect.WithClientOptions(opts...),
		),
		parseImageMessages: connect.NewClient[message.ParseImageMessagesRequest, message.ParseImageMessagesResponse](
			httpClient,
			baseURL+FriendMessageServiceParseImageMessagesProcedure,
			connect.WithSchema(friendMessageServiceMethods.ByName("ParseImageMessages")),
			connect.WithClientOptions(opts...),
		),
	}
}

// friendMessageServiceClient implements FriendMessageServiceClient.
type friendMessageServiceClient struct {
	listFriendMessages  *connect.Client[message.ListFriendMessagesRequest, message.ListFriendMessagesResponse]
	createFriendMessage *connect.Client[message.CreateFriendMessageRequest, message.CreateFriendMessageResponse]
	updateFriendMessage *connect.Client[message.UpdateFriendMessageRequest, message.UpdateFriendMessageResponse]
	deleteFriendMessage *connect.Client[message.DeleteFriendMessageRequest, message.DeleteFriendMessageResponse]
	parseImageMessages  *connect.Client[message.ParseImageMessagesRequest, message.ParseImageMessagesResponse]
}

// ListFriendMessages calls message.FriendMessageService.ListFriendMessages.
func (c *friendMessageServiceClient) ListFriendMessages(ctx context.Context, req *connect.Request[message.ListFriendMessagesRequest]) (*connect.Response[message.ListFriendMessagesResponse], error) {
	return c.listFriendMessages.CallUnary(ctx, req)
}

// CreateFriendMessage calls message.FriendMessageService.CreateFriendMessage.
func (c *friendMessageServiceClient) CreateFriendMessage(ctx context.Context, req *connect.Request[message.CreateFriendMessageRequest]) (*connect.Response[message.CreateFriendMessageResponse], error) {
	return c.createFriendMessage.CallUnary(ctx, req)
}

// UpdateFriendMessage calls message.FriendMessageService.UpdateFriendMessage.
func (c *friendMessageServiceClient) UpdateFriendMessage(ctx context.Context, req *connect.Request[message.UpdateFriendMessageRequest]) (*connect.Response[message.UpdateFriendMessageResponse], error) {
	return c.updateFriendMessage.CallUnary(ctx, req)
}

// DeleteFriendMessage calls message.FriendMessageService.DeleteFriendMessage.
func (c *friendMessageServiceClient) DeleteFriendMessage(ctx context.Context, req *connect.Request[message.DeleteFriendMessageRequest]) (*connect.Response[message.DeleteFriendMessageResponse], error) {
	return c.deleteFriendMessage.CallUnary(ctx, req)
}

// ParseImageMessages calls message.FriendMessageService.ParseImageMessages.
func (c *friendMessageServiceClient) ParseImageMessages(ctx context.Context, req *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error) {
	return c.parseImageMessages.CallUnary(ctx, req)
}

// FriendMessageServiceHandler is an implementation of the message.FriendMessageService service.
//
// Deprecated: do not use.
type FriendMessageServiceHandler interface {
	ListFriendMessages(context.Context, *connect.Request[message.ListFriendMessagesRequest]) (*connect.Response[message.ListFriendMessagesResponse], error)
	CreateFriendMessage(context.Context, *connect.Request[message.CreateFriendMessageRequest]) (*connect.Response[message.CreateFriendMessageResponse], error)
	UpdateFriendMessage(context.Context, *connect.Request[message.UpdateFriendMessageRequest]) (*connect.Response[message.UpdateFriendMessageResponse], error)
	DeleteFriendMessage(context.Context, *connect.Request[message.DeleteFriendMessageRequest]) (*connect.Response[message.DeleteFriendMessageResponse], error)
	ParseImageMessages(context.Context, *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error)
}

// NewFriendMessageServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
//
// Deprecated: do not use.
func NewFriendMessageServiceHandler(svc FriendMessageServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	friendMessageServiceMethods := message.File_proto_message_message_proto.Services().ByName("FriendMessageService").Methods()
	friendMessageServiceListFriendMessagesHandler := connect.NewUnaryHandler(
		FriendMessageServiceListFriendMessagesProcedure,
		svc.ListFriendMessages,
		connect.WithSchema(friendMessageServiceMethods.ByName("ListFriendMessages")),
		connect.WithHandlerOptions(opts...),
	)
	friendMessageServiceCreateFriendMessageHandler := connect.NewUnaryHandler(
		FriendMessageServiceCreateFriendMessageProcedure,
		svc.CreateFriendMessage,
		connect.WithSchema(friendMessageServiceMethods.ByName("CreateFriendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	friendMessageServiceUpdateFriendMessageHandler := connect.NewUnaryHandler(
		FriendMessageServiceUpdateFriendMessageProcedure,
		svc.UpdateFriendMessage,
		connect.WithSchema(friendMessageServiceMethods.ByName("UpdateFriendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	friendMessageServiceDeleteFriendMessageHandler := connect.NewUnaryHandler(
		FriendMessageServiceDeleteFriendMessageProcedure,
		svc.DeleteFriendMessage,
		connect.WithSchema(friendMessageServiceMethods.ByName("DeleteFriendMessage")),
		connect.WithHandlerOptions(opts...),
	)
	friendMessageServiceParseImageMessagesHandler := connect.NewUnaryHandler(
		FriendMessageServiceParseImageMessagesProcedure,
		svc.ParseImageMessages,
		connect.WithSchema(friendMessageServiceMethods.ByName("ParseImageMessages")),
		connect.WithHandlerOptions(opts...),
	)
	return "/message.FriendMessageService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FriendMessageServiceListFriendMessagesProcedure:
			friendMessageServiceListFriendMessagesHandler.ServeHTTP(w, r)
		case FriendMessageServiceCreateFriendMessageProcedure:
			friendMessageServiceCreateFriendMessageHandler.ServeHTTP(w, r)
		case FriendMessageServiceUpdateFriendMessageProcedure:
			friendMessageServiceUpdateFriendMessageHandler.ServeHTTP(w, r)
		case FriendMessageServiceDeleteFriendMessageProcedure:
			friendMessageServiceDeleteFriendMessageHandler.ServeHTTP(w, r)
		case FriendMessageServiceParseImageMessagesProcedure:
			friendMessageServiceParseImageMessagesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFriendMessageServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFriendMessageServiceHandler struct{}

func (UnimplementedFriendMessageServiceHandler) ListFriendMessages(context.Context, *connect.Request[message.ListFriendMessagesRequest]) (*connect.Response[message.ListFriendMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.FriendMessageService.ListFriendMessages is not implemented"))
}

func (UnimplementedFriendMessageServiceHandler) CreateFriendMessage(context.Context, *connect.Request[message.CreateFriendMessageRequest]) (*connect.Response[message.CreateFriendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.FriendMessageService.CreateFriendMessage is not implemented"))
}

func (UnimplementedFriendMessageServiceHandler) UpdateFriendMessage(context.Context, *connect.Request[message.UpdateFriendMessageRequest]) (*connect.Response[message.UpdateFriendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.FriendMessageService.UpdateFriendMessage is not implemented"))
}

func (UnimplementedFriendMessageServiceHandler) DeleteFriendMessage(context.Context, *connect.Request[message.DeleteFriendMessageRequest]) (*connect.Response[message.DeleteFriendMessageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.FriendMessageService.DeleteFriendMessage is not implemented"))
}

func (UnimplementedFriendMessageServiceHandler) ParseImageMessages(context.Context, *connect.Request[message.ParseImageMessagesRequest]) (*connect.Response[message.ParseImageMessagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("message.FriendMessageService.ParseImageMessages is not implemented"))
}
