// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/translate/translate.proto

package translate

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	History       string                 `protobuf:"bytes,4,opt,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_proto_translate_translate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translate_translate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_proto_translate_translate_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TranslateRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TranslateRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TranslateRequest) GetHistory() string {
	if x != nil {
		return x.History
	}
	return ""
}

type TranslateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_proto_translate_translate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translate_translate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_proto_translate_translate_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TranslateFriendMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FriendMessageId string                 `protobuf:"bytes,1,opt,name=friend_message_id,json=friendMessageId,proto3" json:"friend_message_id,omitempty"`
	From            string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To              string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranslateFriendMessageRequest) Reset() {
	*x = TranslateFriendMessageRequest{}
	mi := &file_proto_translate_translate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateFriendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateFriendMessageRequest) ProtoMessage() {}

func (x *TranslateFriendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translate_translate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateFriendMessageRequest.ProtoReflect.Descriptor instead.
func (*TranslateFriendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_translate_translate_proto_rawDescGZIP(), []int{2}
}

func (x *TranslateFriendMessageRequest) GetFriendMessageId() string {
	if x != nil {
		return x.FriendMessageId
	}
	return ""
}

func (x *TranslateFriendMessageRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TranslateFriendMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type TranslateFriendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateFriendMessageResponse) Reset() {
	*x = TranslateFriendMessageResponse{}
	mi := &file_proto_translate_translate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateFriendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateFriendMessageResponse) ProtoMessage() {}

func (x *TranslateFriendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translate_translate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateFriendMessageResponse.ProtoReflect.Descriptor instead.
func (*TranslateFriendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_translate_translate_proto_rawDescGZIP(), []int{3}
}

func (x *TranslateFriendMessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TranslateV2Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatSessionId   string                 `protobuf:"bytes,1,opt,name=chat_session_id,json=chatSessionId,proto3" json:"chat_session_id,omitempty"`
	TargetMessageId string                 `protobuf:"bytes,2,opt,name=target_message_id,json=targetMessageId,proto3" json:"target_message_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranslateV2Request) Reset() {
	*x = TranslateV2Request{}
	mi := &file_proto_translate_translate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateV2Request) ProtoMessage() {}

func (x *TranslateV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translate_translate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateV2Request.ProtoReflect.Descriptor instead.
func (*TranslateV2Request) Descriptor() ([]byte, []int) {
	return file_proto_translate_translate_proto_rawDescGZIP(), []int{4}
}

func (x *TranslateV2Request) GetChatSessionId() string {
	if x != nil {
		return x.ChatSessionId
	}
	return ""
}

func (x *TranslateV2Request) GetTargetMessageId() string {
	if x != nil {
		return x.TargetMessageId
	}
	return ""
}

type TranslateV2Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMessageId  string                 `protobuf:"bytes,1,opt,name=new_message_id,json=newMessageId,proto3" json:"new_message_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateV2Response) Reset() {
	*x = TranslateV2Response{}
	mi := &file_proto_translate_translate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateV2Response) ProtoMessage() {}

func (x *TranslateV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_translate_translate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateV2Response.ProtoReflect.Descriptor instead.
func (*TranslateV2Response) Descriptor() ([]byte, []int) {
	return file_proto_translate_translate_proto_rawDescGZIP(), []int{5}
}

func (x *TranslateV2Response) GetNewMessageId() string {
	if x != nil {
		return x.NewMessageId
	}
	return ""
}

func (x *TranslateV2Response) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_translate_translate_proto protoreflect.FileDescriptor

const file_proto_translate_translate_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/translate/translate.proto\x12\ttranslate\x1a\x1cgoogle/api/annotations.proto\"j\n" +
	"\x10TranslateRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\ahistory\x18\x04 \x01(\tR\ahistory\"-\n" +
	"\x11TranslateResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"o\n" +
	"\x1dTranslateFriendMessageRequest\x12*\n" +
	"\x11friend_message_id\x18\x01 \x01(\tR\x0ffriendMessageId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\":\n" +
	"\x1eTranslateFriendMessageResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"h\n" +
	"\x12TranslateV2Request\x12&\n" +
	"\x0fchat_session_id\x18\x01 \x01(\tR\rchatSessionId\x12*\n" +
	"\x11target_message_id\x18\x02 \x01(\tR\x0ftargetMessageId\"U\n" +
	"\x13TranslateV2Response\x12$\n" +
	"\x0enew_message_id\x18\x01 \x01(\tR\fnewMessageId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2\xbe\x03\n" +
	"\x10TranslateService\x12x\n" +
	"\tTranslate\x12\x1b.translate.TranslateRequest\x1a\x1c.translate.TranslateResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/translate.TranslateService/Translate\x12\xac\x01\n" +
	"\x16TranslateFriendMessage\x12(.translate.TranslateFriendMessageRequest\x1a).translate.TranslateFriendMessageResponse\"=\x82\xd3\xe4\x93\x027:\x01*\"2/translate.TranslateService/TranslateFriendMessage\x12\x80\x01\n" +
	"\vTranslateV2\x12\x1d.translate.TranslateV2Request\x1a\x1e.translate.TranslateV2Response\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/translate.TranslateService/TranslateV2B\x1cZ\x1aapp_server/proto/translateb\x06proto3"

var (
	file_proto_translate_translate_proto_rawDescOnce sync.Once
	file_proto_translate_translate_proto_rawDescData []byte
)

func file_proto_translate_translate_proto_rawDescGZIP() []byte {
	file_proto_translate_translate_proto_rawDescOnce.Do(func() {
		file_proto_translate_translate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_translate_translate_proto_rawDesc), len(file_proto_translate_translate_proto_rawDesc)))
	})
	return file_proto_translate_translate_proto_rawDescData
}

var file_proto_translate_translate_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_translate_translate_proto_goTypes = []any{
	(*TranslateRequest)(nil),               // 0: translate.TranslateRequest
	(*TranslateResponse)(nil),              // 1: translate.TranslateResponse
	(*TranslateFriendMessageRequest)(nil),  // 2: translate.TranslateFriendMessageRequest
	(*TranslateFriendMessageResponse)(nil), // 3: translate.TranslateFriendMessageResponse
	(*TranslateV2Request)(nil),             // 4: translate.TranslateV2Request
	(*TranslateV2Response)(nil),            // 5: translate.TranslateV2Response
}
var file_proto_translate_translate_proto_depIdxs = []int32{
	0, // 0: translate.TranslateService.Translate:input_type -> translate.TranslateRequest
	2, // 1: translate.TranslateService.TranslateFriendMessage:input_type -> translate.TranslateFriendMessageRequest
	4, // 2: translate.TranslateService.TranslateV2:input_type -> translate.TranslateV2Request
	1, // 3: translate.TranslateService.Translate:output_type -> translate.TranslateResponse
	3, // 4: translate.TranslateService.TranslateFriendMessage:output_type -> translate.TranslateFriendMessageResponse
	5, // 5: translate.TranslateService.TranslateV2:output_type -> translate.TranslateV2Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_translate_translate_proto_init() }
func file_proto_translate_translate_proto_init() {
	if File_proto_translate_translate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_translate_translate_proto_rawDesc), len(file_proto_translate_translate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_translate_translate_proto_goTypes,
		DependencyIndexes: file_proto_translate_translate_proto_depIdxs,
		MessageInfos:      file_proto_translate_translate_proto_msgTypes,
	}.Build()
	File_proto_translate_translate_proto = out.File
	file_proto_translate_translate_proto_goTypes = nil
	file_proto_translate_translate_proto_depIdxs = nil
}
